// lib/tours.ts

export interface ItineraryDay {
  day: number
  title: string
  description: string
}

export interface Tour {
  featured: boolean
  name: string
  destinations: string[]
  bestTime: string[]
  priceFrom: number
  id: string
  slug: string
  title: string
  description: string
  shortDescription?: string
  price: number
  currency: string
  originalPrice?: number
  image: string
  gallery?: string[]
  duration: string
  groupSize: string
  difficulty: string
  url: string
  region: string
  country: "Kenya" | "Tanzania" | "Rwanda" | "Uganda" | "Multi-Country"
  highlights: string[]
  included: string[]
  excluded: string[]
  itinerary: ItineraryDay[]
  rating: number
  reviewCount: number
  metaTitle: string
  metaDescription: string
  keywords: string[]
  category: "Safari" | "Trekking" | "Cultural" | "Beach" | "Adventure" | "Luxury" | "Budget" | "Accessible"
  isPopular?: boolean
  isOnOffer?: boolean
  bestFor?: string[]
  bookingUrl: string
  internalLinks?: Array<{ url: string; label: string }>
  postId?: string
}

export const tours: Tour[] = [
  {
    id: "kenya-masai-mara",
    slug: "masai-mara-luxury-safari",
    image: "/masai-mara-migration.jpg",
    title: "Masai Mara Luxury Safari",
    description: "Experience the wildlife of Masai Mara with luxury accommodations and expert guides. Includes game drives and meals.",
    price: 3500,
    currency: "USD",
    originalPrice: 4200,
    duration: "3 days",
    groupSize: "2-6",
    difficulty: "Easy",
    url: "/tours/masai-mara-luxury-safari",
    region: "East Africa",
    country: "Kenya",
    highlights: ["Great Migration", "Big Five", "Luxury Lodges", "Hot Air Balloon"],
    included: ["All meals", "Park fees", "4x4 game drives", "Luxury accommodation", "Airport transfers"],
    excluded: ["International flights", "Tips", "Alcoholic drinks", "Laundry"],
    itinerary: [
      { day: 1, title: "Arrival & Lodge Check-in", description: "Fly into Nairobi, transfer to luxury lodge in Masai Mara." },
      { day: 2, title: "Morning & Evening Game Drives", description: "Full day exploring the Mara with expert guides." },
      { day: 3, title: "Hot Air Balloon & Departure", description: "Optional balloon ride at dawn, then depart." },
    ],
    rating: 4.8,
    reviewCount: 128,
    metaTitle: "Masai Mara Luxury Safari | Jae Travel Expeditions",
    metaDescription: "Book your Masai Mara Luxury Safari with Jae Travel. Enjoy game drives, luxury lodges, and expert guides in Kenya's most iconic park.",
    keywords: ["Masai Mara Safari", "Luxury Kenya Safari", "Kenya Wildlife Tours", "Masai Mara game drives"],
    bookingUrl: "/booking/masai-mara-luxury-safari",
    category: "Luxury",
    isOnOffer: true,
    isPopular: true,
    featured: true,
    name: "Masai Mara Luxury Safari",
    destinations: ["Masai Mara National Reserve"],
    bestTime: ["July-October", "December-March"],
    priceFrom: 3500
  },
  {
    id: "kenya-amboseli",
    slug: "amboseli-safari",
    image: "/Amboseli-National-Park-Elephantsssss.jpg",
    title: "Amboseli Safari Adventure",
    description: "Explore Amboseli National Park with guided game drives and spectacular views of Mount Kilimanjaro.",
    price: 2800,
    currency: "USD",
    duration: "3 days",
    groupSize: "2-8",
    difficulty: "Easy",
    url: "/tours/amboseli-safari",
    region: "East Africa",
    country: "Kenya",
    highlights: ["Mount Kilimanjaro Views", "Large Elephant Herds", "Bird Watching"],
    included: ["Park fees", "Meals", "Game drives", "Accommodation", "Transfers"],
    excluded: ["Flights", "Tips", "Drinks"],
    itinerary: [
      { day: 1, title: "Arrival & Lodge Check-in", description: "Fly into Amboseli and settle into your lodge." },
      { day: 2, title: "Morning & Evening Game Drives", description: "Track elephants with Kilimanjaro backdrop." },
      { day: 3, title: "Departure", description: "Morning game drive and return flight." },
    ],
    rating: 4.7,
    reviewCount: 95,
    metaTitle: "Amboseli Safari Adventure | Jae Travel Expeditions",
    metaDescription: "Discover Amboseli Safari with breathtaking views of Mount Kilimanjaro. Guided game drives and luxury stays included.",
    keywords: ["Amboseli Safari", "Kenya Tours", "Kilimanjaro Safari", "Amboseli National Park"],
    bookingUrl: "/booking/amboseli-safari",
    category: "Safari",
    featured: false,
    name: "Amboseli Safari Adventure",
    destinations: ["Amboseli National Park"],
    bestTime: ["June-October", "January-February"],
    priceFrom: 2800
  },
  {
    id: "tanzania-serengeti",
    slug: "serengeti-migration-tour",
    image: "/Serengeti-National-Park-Africa-Kenya-Safaris2.jpg",
    title: "Serengeti Migration Safari",
    description: "Witness the Great Migration in Serengeti with guided tours and comfortable lodges. Includes daily game drives and meals.",
    price: 4200,
    currency: "USD",
    originalPrice: 5000,
    duration: "4 days",
    groupSize: "4-10",
    difficulty: "Moderate",
    url: "/tours/serengeti-migration-tour",
    region: "East Africa",
    country: "Tanzania",
    highlights: ["Great Migration", "Big Cats", "Endless Plains"],
    included: ["All meals", "Park fees", "Game drives", "Guide", "Internal flights"],
    excluded: ["International flights", "Visa", "Tips"],
    itinerary: [
      { day: 1, title: "Arrival in Serengeti", description: "Fly into Serengeti and transfer to camp." },
      { day: 2, title: "Full Day Migration Tracking", description: "Follow the herds with expert guides." },
      { day: 3, title: "Morning Game Drive", description: "Final drive before departure." },
      { day: 4, title: "Cultural Visit & Departure", description: "Visit local community and fly out." },
    ],
    rating: 4.9,
    reviewCount: 97,
    metaTitle: "Serengeti Migration Safari | Jae Travel Expeditions",
    metaDescription: "Experience the Great Migration in Serengeti with expert guides, luxury lodges, and unforgettable wildlife encounters.",
    keywords: ["Serengeti Migration", "Tanzania Safari", "Great Migration Tour", "Serengeti National Park"],
    bookingUrl: "/booking/serengeti-migration-tour",
    category: "Safari",
    isOnOffer: true,
    isPopular: true,
    featured: true,
    name: "Serengeti Migration Safari",
    destinations: ["Serengeti National Park"],
    bestTime: ["June-October", "December-March"],
    priceFrom: 4200
  },
  {
    id: "tanzania-ngorongoro",
    slug: "ngorongoro-crater-safari",
    image: "/Ngorongoro-Crater.jpg",
    title: "Ngorongoro Crater Safari",
    description: "Explore the Ngorongoro Crater with guided game drives and luxury accommodation. Ideal for families and photographers.",
    price: 2800,
    currency: "USD",
    duration: "3 days",
    groupSize: "2-8",
    difficulty: "Easy",
    url: "/tours/ngorongoro-crater-safari",
    region: "East Africa",
    country: "Tanzania",
    highlights: ["World's Largest Caldera", "Black Rhino", "Big Five"],
    included: ["Park fees", "Meals", "Crater tour", "Accommodation"],
    excluded: ["Flights", "Tips"],
    itinerary: [
      { day: 1, title: "Arrival & Lodge Check-in", description: "Arrive and settle into rim lodge." },
      { day: 2, title: "Full-Day Crater Tour", description: "Descend into the crater for wildlife viewing." },
      { day: 3, title: "Departure", description: "Morning at leisure and fly out." },
    ],
    rating: 4.7,
    reviewCount: 64,
    metaTitle: "Ngorongoro Crater Safari | Jae Travel Expeditions",
    metaDescription: "Book your Ngorongoro Crater Safari with Jae Travel. A perfect adventure for families, photographers, and nature lovers.",
    keywords: ["Ngorongoro Safari", "Tanzania Wildlife Tours", "Family Safari", "Crater Tour"],
    bookingUrl: "/booking/ngorongoro-crater-safari",
    category: "Safari",
    featured: false,
    name: "Ngorongoro Crater Safari",
    destinations: ["Ngorongoro Conservation Area"],
    bestTime: ["June-September", "January-February"],
    priceFrom: 2800
  },
  {
    id: "uganda-bwindi",
    slug: "bwindi-gorilla-trek",
    image: "/bwindi-forest-uganda-gorilla-safaris.jpg",
    title: "Bwindi Gorilla Trekking",
    description: "Trek the dense forests of Bwindi to see mountain gorillas up close with expert guides. Includes park fees and accommodations.",
    price: 3200,
    currency: "USD",
    duration: "3 days",
    groupSize: "1-8",
    difficulty: "Challenging",
    url: "/tours/bwindi-gorilla-trek",
    region: "East Africa",
    country: "Uganda",
    highlights: ["Gorilla Trek", "Rainforest", "Batwa Culture"],
    included: ["Gorilla permit", "Guide", "Accommodation", "Meals", "Transfers"],
    excluded: ["Flights", "Visa", "Tips"],
    itinerary: [
      { day: 1, title: "Arrival at Lodge", description: "Transfer to Bwindi and briefing." },
      { day: 2, title: "Gorilla Trekking", description: "Full day tracking mountain gorillas." },
      { day: 3, title: "Cultural Visit & Departure", description: "Visit Batwa community and depart." },
    ],
    rating: 4.8,
    reviewCount: 80,
    metaTitle: "Bwindi Gorilla Trekking | Jae Travel Expeditions",
    metaDescription: "Embark on a Bwindi Gorilla Trekking safari. See mountain gorillas up close and explore Uganda's lush forests.",
    keywords: ["Bwindi Gorilla Trek", "Uganda Safari", "Gorilla Trekking Tours", "Mountain Gorillas"],
    bookingUrl: "/booking/bwindi-gorilla-trek",
    category: "Trekking",
    featured: false,
    name: "Bwindi Gorilla Trekking",
    destinations: ["Bwindi Impenetrable National Park"],
    bestTime: ["June-September", "December-February"],
    priceFrom: 3200
  },
  {
    id: "rwanda-volcanoes",
    slug: "volcanoes-national-park-safari",
    image: "/Volcanoes-National-Park-Rwanda-Natural-World-Kenya-Safaris.jpg",
    title: "Rwanda Gorilla Safari",
    description: "Explore Volcanoes National Park in Rwanda to trek gorillas and experience local culture.",
    price: 3800,
    currency: "USD",
    originalPrice: 4500,
    duration: "3 days",
    groupSize: "1-8",
    difficulty: "Challenging",
    url: "/tours/volcanoes-national-park-safari",
    region: "East Africa",
    country: "Rwanda",
    highlights: ["Gorilla Trek", "Volcanoes", "Cultural Immersion"],
    included: ["Gorilla permit", "Guide", "Accommodation", "Meals"],
    excluded: ["Flights", "Visa"],
    itinerary: [
      { day: 1, title: "Arrival & Lodge Check-in", description: "Arrive in Kigali, transfer to lodge." },
      { day: 2, title: "Gorilla Trekking", description: "Trek to see mountain gorillas." },
      { day: 3, title: "Cultural Tour & Departure", description: "Visit local community and fly out." },
    ],
    rating: 4.9,
    reviewCount: 72,
    metaTitle: "Rwanda Gorilla Safari | Jae Travel Expeditions",
    metaDescription: "Book your Rwanda Gorilla Safari in Volcanoes National Park. Trek gorillas, enjoy cultural tours, and luxury accommodations.",
    keywords: ["Rwanda Gorilla Safari", "Volcanoes National Park", "Gorilla Trekking Rwanda", "Rwanda Tours"],
    bookingUrl: "/booking/volcanoes-national-park-safari",
    category: "Trekking",
    isOnOffer: true,
    featured: true,
    name: "Rwanda Gorilla Safari",
    destinations: ["Volcanoes National Park"],
    bestTime: ["June-September", "December-February"],
    priceFrom: 3800
  },
  {
    id: "1",
    slug: "masai-mara-safari-adventure",
    image: "/magestic-maasai-serengeti.jpg",
    title: "Masai Mara Safari Adventure",
    description: "Experience the great migration and witness the Big Five in Kenya's most iconic national reserve.",
    price: 1200,
    currency: "USD",
    duration: "5 days",
    groupSize: "2-12",
    difficulty: "Easy",
    url: "/tours/masai-mara-safari-adventure",
    region: "East Africa",
    country: "Kenya",
    highlights: ["Great Migration", "Big Five", "River Crossings", "Bush Breakfast"],
    included: ["Park fees", "Meals", "4x4 vehicle", "Guide", "Transfers"],
    excluded: ["Flights", "Tips", "Drinks"],
    itinerary: [
      { day: 1, title: "Arrival & Lodge Check-in", description: "Fly into Mara and settle in." },
      { day: 2, title: "Full Day Game Drive", description: "Morning and afternoon drives." },
      { day: 3, title: "Migration River Crossing", description: "Witness the dramatic crossings." },
      { day: 4, title: "Bush Breakfast", description: "Breakfast in the wild." },
      { day: 5, title: "Departure", description: "Final game drive and fly out." },
    ],
    rating: 4.9,
    reviewCount: 156,
    metaTitle: "Masai Mara Safari Adventure - 5 Days | Jae Travel Expeditions",
    metaDescription: "Experience the great migration and witness the Big Five in Masai Mara. 5-day safari with expert guides.",
    keywords: ["Masai Mara", "Kenya Safari", "Big Five", "Great Migration", "5 day safari"],
    bookingUrl: "/booking/masai-mara-safari-adventure",
    category: "Safari",
    isPopular: true,
    featured: true,
    name: "Masai Mara Safari Adventure",
    destinations: ["Masai Mara National Reserve"],
    bestTime: ["July-October"],
    priceFrom: 1200
  },
  {
    id: "2",
    slug: "amboseli-elephant-safari",
    image: "/amboseli-elephants-00007.jpg",
    title: "Amboseli Elephant Safari",
    description: "Get close to elephants with Mount Kilimanjaro backdrop in Amboseli National Park.",
    price: 980,
    currency: "USD",
    duration: "4 days",
    groupSize: "2-10",
    difficulty: "Easy",
    url: "/tours/amboseli-elephant-safari",
    region: "East Africa",
    country: "Kenya",
    highlights: ["Elephant Herds", "Kilimanjaro Views", "Swamps"],
    included: ["Park fees", "Meals", "Game drives", "Accommodation"],
    excluded: ["Flights", "Tips"],
    itinerary: [
      { day: 1, title: "Arrival & Lodge Check-in", description: "Fly into Amboseli." },
      { day: 2, title: "Elephant Viewing", description: "Morning and afternoon drives." },
      { day: 3, title: "Swamp Walk", description: "Guided walk in the swamps." },
      { day: 4, title: "Departure", description: "Final game drive and fly out." },
    ],
    rating: 4.7,
    reviewCount: 89,
    metaTitle: "Amboseli Elephant Safari - 4 Days | Jae Travel Expeditions",
    metaDescription: "Get close to elephants with Mount Kilimanjaro backdrop. 4-day Amboseli safari.",
    keywords: ["Amboseli", "Elephant Safari", "Kilimanjaro", "Kenya Wildlife", "Elephant Tours"],
    bookingUrl: "/booking/amboseli-elephant-safari",
    category: "Safari",
    featured: false,
    name: "Amboseli Elephant Safari",
    destinations: ["Amboseli National Park"],
    bestTime: ["June-October", "January-February"],
    priceFrom: 980
  },
  {
    id: "3",
    slug: "samburu-game-reserve",
    image: "/Samburu_National_Reserve,_Kenya-26December2012.jpg",
    title: "Samburu Game Reserve",
    description: "Discover unique wildlife in the northern frontier.",
    price: 750,
    currency: "USD",
    duration: "3 days",
    groupSize: "2-8",
    difficulty: "Easy",
    url: "/tours/samburu-game-reserve",
    region: "East Africa",
    country: "Kenya",
    highlights: ["Grevy's Zebra", "Reticulated Giraffe", "Samburu Five"],
    included: ["Park fees", "Meals", "Game drives", "Accommodation"],
    excluded: ["Flights", "Tips"],
    itinerary: [
      { day: 1, title: "Arrival & Lodge Check-in", description: "Fly into Samburu." },
      { day: 2, title: "Full-Day Game Drives", description: "Morning and afternoon drives." },
      { day: 3, title: "Departure", description: "Morning drive and fly out." },
    ],
    rating: 4.6,
    reviewCount: 45,
    metaTitle: "Samburu Game Reserve Safari - 3 Days | Jae Travel Expeditions",
    metaDescription: "Discover unique wildlife in northern Kenya at Samburu Game Reserve.",
    keywords: ["Samburu", "Game Reserve", "Northern Kenya", "Unique Wildlife", "Samburu National Reserve"],
    bookingUrl: "/booking/samburu-game-reserve",
    category: "Safari",
    featured: false,
    name: "Samburu Game Reserve Safari",
    destinations: ["Samburu National Reserve"],
    bestTime: ["June-October", "January-March"],
    priceFrom: 750
  },
  {
    id: "4",
    slug: "lake-nakuru-flamingo-spectacle",
    image: "/lake-nakuru-flamingos-in-red-sunset-590x390.jpg",
    title: "Lake Nakuru Flamingo Tour",
    description: "Witness thousands of flamingos in their natural habitat.",
    price: 450,
    currency: "USD",
    originalPrice: 550,
    duration: "2 days",
    groupSize: "2-10",
    difficulty: "Easy",
    url: "/tours/lake-nakuru-flamingo-spectacle",
    region: "East Africa",
    country: "Kenya",
    highlights: ["Flamingo Flocks", "Rhino Sanctuary", "Bird Watching"],
    included: ["Park fees", "Meals", "Game drive", "Accommodation"],
    excluded: ["Flights", "Tips"],
    itinerary: [
      { day: 1, title: "Arrival & Afternoon Game Drive", description: "Drive to Lake Nakuru." },
      { day: 2, title: "Morning Bird Watching & Departure", description: "Final viewing and depart." },
    ],
    rating: 4.5,
    reviewCount: 67,
    metaTitle: "Lake Nakuru Flamingo Tour - 2 Days | Jae Travel Expeditions",
    metaDescription: "Witness thousands of flamingos at Lake Nakuru. Perfect for bird watchers.",
    keywords: ["Lake Nakuru", "Flamingos", "Bird Watching", "Kenya", "Flamingo Tour"],
    bookingUrl: "/booking/lake-nakuru-flamingo-spectacle",
    category: "Safari",
    isOnOffer: true,
    featured: false,
    name: "Lake Nakuru Flamingo Tour",
    destinations: ["Lake Nakuru National Park"],
    bestTime: ["July-October", "January-March"],
    priceFrom: 450
  },
  {
    id: "5",
    slug: "tsavo-east-west-adventure",
    image: "/tsavo-west-national-park-chyulu-gate.jpg.webp",
    title: "Tsavo East & West Safari",
    description: "Explore Kenya's largest national park.",
    price: 1350,
    currency: "USD",
    duration: "6 days",
    groupSize: "2-10",
    difficulty: "Moderate",
    url: "/tours/tsavo-east-west-adventure",
    region: "East Africa",
    country: "Kenya",
    highlights: ["Red Elephants", "Mzima Springs", "Lions", "Lava Fields"],
    included: ["Park fees", "Meals", "Game drives", "Accommodation", "Transfers"],
    excluded: ["Flights", "Tips"],
    itinerary: [
      { day: 1, title: "Arrival at Tsavo East", description: "Begin in Tsavo East." },
      { day: 2, title: "Tsavo East Game Drives", description: "Morning and afternoon drives." },
      { day: 3, title: "Tsavo East Full Day", description: "Explore further." },
      { day: 4, title: "Transfer to Tsavo West", description: "Travel to West." },
      { day: 5, title: "Tsavo West Game Drives", description: "Mzima Springs and lava." },
      { day: 6, title: "Departure", description: "Final drive and depart." },
    ],
    rating: 4.8,
    reviewCount: 73,
    metaTitle: "Tsavo East & West Safari - 6 Days | Jae Travel Expeditions",
    metaDescription: "Explore Kenya's largest national park with 6-day safari.",
    keywords: ["Tsavo", "National Park", "Kenya Safari", "Red Elephants", "Tsavo East and West"],
    bookingUrl: "/booking/tsavo-east-west-adventure",
    category: "Safari",
    featured: false,
    name: "Tsavo East & West Safari",
    destinations: ["Tsavo East National Park", "Tsavo West National Park"],
    bestTime: ["June-October", "January-March"],
    priceFrom: 1350
  },
  {
    id: "6",
    slug: "mombasa-coastal-safari",
    image: "/Mombasa-beach-2-1960x800.webp",
    title: "Mombasa Beach & Safari",
    description: "Combine safari adventures with beach relaxation.",
    price: 1600,
    currency: "USD",
    duration: "7 days",
    groupSize: "2-8",
    difficulty: "Easy",
    url: "/tours/mombasa-coastal-safari",
    region: "East Africa",
    country: "Kenya",
    highlights: ["Tsavo Safari", "Mombasa Beach", "Snorkeling", "Cultural Tours"],
    included: ["Park fees", "Meals", "Game drives", "Beach resort", "Water sports"],
    excluded: ["Flights", "Tips"],
    itinerary: [
      { day: 1, title: "Safari in Tsavo East", description: "Game drives." },
      { day: 2, title: "Tsavo East Full Day", description: "Continue safari." },
      { day: 3, title: "Tsavo East", description: "Final safari day." },
      { day: 4, title: "Transfer to Mombasa", description: "Beach arrival." },
      { day: 5, title: "Beach Relaxation", description: "Free day." },
      { day: 6, title: "Water Sports", description: "Snorkeling, diving." },
      { day: 7, title: "Departure", description: "Fly out." },
    ],
    rating: 4.7,
    reviewCount: 91,
    metaTitle: "Mombasa Beach & Safari - 7 Days | Jae Travel Expeditions",
    metaDescription: "Combine safari and beach relaxation in Mombasa.",
    keywords: ["Mombasa", "Beach Safari", "Coastal Kenya", "Safari and Beach", "Mombasa Tours"],
    bookingUrl: "/booking/mombasa-coastal-safari",
    category: "Beach",
    featured: false,
    name: "Mombasa Beach & Safari",
    destinations: ["Tsavo National Park", "Mombasa Coast"],
    bestTime: ["June-October", "December-March"],
    priceFrom: 1600
  },
  {
    id: "7",
    slug: "mount-kenya-climbing-expedition",
    image: "/mt-kenya.jpg",
    title: "Mount Kenya Climbing",
    description: "Challenge yourself with Africa's second highest peak.",
    price: 1100,
    currency: "USD",
    duration: "5 days",
    groupSize: "2-6",
    difficulty: "Challenging",
    url: "/tours/mount-kenya-climbing-expedition",
    region: "East Africa",
    country: "Kenya",
    highlights: ["Point Lenana", "Alpine Flora", "Wildlife", "Summit"],
    included: ["Guide", "Porters", "Meals", "Camping gear", "Park fees"],
    excluded: ["Flights", "Tips", "Personal gear"],
    itinerary: [
      { day: 1, title: "Arrival & Briefing", description: "Gear check and briefing." },
      { day: 2, title: "Climb to Camp 1", description: "Ascent begins." },
      { day: 3, title: "Camp 2", description: "Continue climbing." },
      { day: 4, title: "Summit Point Lenana", description: "Dawn summit." },
      { day: 5, title: "Descent & Departure", description: "Return to base." },
    ],
    rating: 4.4,
    reviewCount: 38,
    metaTitle: "Mount Kenya Climbing Expedition - 5 Days | Jae Travel Expeditions",
    metaDescription: "Challenge yourself climbing Africa's second highest peak.",
    keywords: ["Mount Kenya", "Climbing", "Trekking", "Mountain Expedition", "Point Lenana"],
    bookingUrl: "/booking/mount-kenya-climbing-expedition",
    category: "Trekking",
    featured: false,
    name: "Mount Kenya Climbing Expedition",
    destinations: ["Mount Kenya National Park"],
    bestTime: ["January-February", "July-October"],
    priceFrom: 1100
  },
  {
    id: "8",
    slug: "laikipia-conservancy",
    image: "/laikipia-kenya-photography-safari.jpg",
    title: "Laikipia Conservancy",
    description: "Experience conservation in action.",
    price: 1250,
    currency: "USD",
    duration: "4 days",
    groupSize: "2-6",
    difficulty: "Easy",
    url: "/tours/laikipia-conservancy",
    region: "East Africa",
    country: "Kenya",
    highlights: ["Conservation", "Community", "Wildlife", "Night Drives"],
    included: ["All meals", "Activities", "Accommodation", "Guide"],
    excluded: ["Flights", "Tips"],
    itinerary: [
      { day: 1, title: "Arrival & Orientation", description: "Learn about conservation." },
      { day: 2, title: "Game Drives & Activities", description: "Wildlife and community." },
      { day: 3, title: "Full Day Conservation", description: "Hands-on experience." },
      { day: 4, title: "Departure", description: "Final activity and fly out." },
    ],
    rating: 4.8,
    reviewCount: 52,
    metaTitle: "Laikipia Conservancy Experience - 4 Days | Jae Travel Expeditions",
    metaDescription: "Experience conservation in action at Laikipia Conservancy.",
    keywords: ["Laikipia", "Conservancy", "Conservation", "Community Tourism", "Laikipia Kenya"],
    bookingUrl: "/booking/laikipia-conservancy",
    category: "Safari",
    featured: false,
    name: "Laikipia Conservancy Experience",
    destinations: ["Laikipia Plateau"],
    bestTime: ["June-October", "January-March"],
    priceFrom: 1250
  },
  {
    id: "9",
    slug: "hell-gate-lake-naivasha-adventure",
    image: "/Hells-Gate-National-Park.jpg",
    title: "Hell's Gate Adventure",
    description: "Bike and hike through dramatic landscapes.",
    price: 380,
    currency: "USD",
    duration: "2 days",
    groupSize: "2-12",
    difficulty: "Moderate",
    url: "/tours/hell-gate-lake-naivasha-adventure",
    region: "East Africa",
    country: "Kenya",
    highlights: ["Biking", "Gorge Hiking", "Boat Safari", "Wildlife"],
    included: ["Bike rental", "Guide", "Boat safari", "Park fees"],
    excluded: ["Flights", "Tips"],
    itinerary: [
      { day: 1, title: "Biking & Gorge Hiking", description: "Explore Hell's Gate." },
      { day: 2, title: "Boat Safari & Departure", description: "Lake Naivasha and depart." },
    ],
    rating: 4.3,
    reviewCount: 84,
    metaTitle: "Hell's Gate Adventure Tour - 2 Days | Jae Travel Expeditions",
    metaDescription: "Bike and hike through Hell's Gate National Park.",
    keywords: ["Hell's Gate", "Adventure", "Biking", "Lake Naivasha", "Gorge Hiking"],
    bookingUrl: "/booking/hell-gate-lake-naivasha-adventure",
    category: "Adventure",
    featured: false,
    name: "Hell's Gate Adventure",
    destinations: ["Hell's Gate National Park", "Lake Naivasha"],
    bestTime: ["June-October", "January-March"],
    priceFrom: 380
  },
  {
    id: "10",
    slug: "maasai-cultural-experience",
    image: "/magestic-maasai-serengeti.jpg",
    title: "Maasai Cultural Experience",
    description: "Immerse yourself in Maasai culture.",
    price: 650,
    currency: "USD",
    duration: "3 days",
    groupSize: "2-10",
    difficulty: "Easy",
    url: "/tours/maasai-cultural-experience",
    region: "East Africa",
    country: "Kenya",
    highlights: ["Village Tour", "Dances", "Craft Making", "Homestay"],
    included: ["All meals", "Guide", "Cultural activities", "Accommodation"],
    excluded: ["Flights", "Tips"],
    itinerary: [
      { day: 1, title: "Welcome Ceremony", description: "Arrival and traditional welcome." },
      { day: 2, title: "Cultural Activities", description: "Dances, crafts, village life." },
      { day: 3, title: "Departure", description: "Final interactions and depart." },
    ],
    rating: 4.6,
    reviewCount: 96,
    metaTitle: "Maasai Cultural Experience - 3 Days | Jae Travel Expeditions",
    metaDescription: "Immerse yourself in Maasai culture with authentic experience.",
    keywords: ["Maasai", "Cultural Experience", "Kenya Culture", "Traditional Village", "Maasai Village"],
    bookingUrl: "/booking/maasai-cultural-experience",
    category: "Cultural",
    featured: false,
    name: "Maasai Cultural Experience",
    destinations: ["Maasai Mara Region"],
    bestTime: ["Year-round"],
    priceFrom: 650
  },
  {
    id: "11",
    slug: "aberdare-national-park-safari",
    image: "/Aberdare.jpg",
    title: "Aberdare National Park",
    description: "Mountain forest safari experience.",
    price: 720,
    currency: "USD",
    duration: "3 days",
    groupSize: "2-8",
    difficulty: "Easy",
    url: "/tours/aberdare-national-park-safari",
    region: "East Africa",
    country: "Kenya",
    highlights: ["Forest Wildlife", "Waterfalls", "Birds", "Tree Hotels"],
    included: ["Park fees", "Meals", "Game drives", "Accommodation"],
    excluded: ["Flights", "Tips"],
    itinerary: [
      { day: 1, title: "Arrival & Lodge Check-in", description: "Settle into tree hotel." },
      { day: 2, title: "Forest Walks & Game Viewing", description: "Explore the park." },
      { day: 3, title: "Departure", description: "Morning activity and depart." },
    ],
    rating: 4.5,
    reviewCount: 41,
    metaTitle: "Aberdare National Park Safari - 3 Days | Jae Travel Expeditions",
    metaDescription: "Mountain forest safari in Aberdare National Park.",
    keywords: ["Aberdare", "National Park", "Mountain Safari", "Forest Wildlife", "Aberdare Range"],
    bookingUrl: "/booking/aberdare-national-park-safari",
    category: "Safari",
    featured: false,
    name: "Aberdare National Park Safari",
    destinations: ["Aberdare National Park"],
    bestTime: ["June-October", "January-March"],
    priceFrom: 720
  },
  {
    id: "12",
    slug: "diani-beach-safari-combo",
    image: "/Kenia-Mombasa-Diani-Beach-Leopard-Beach-Resort-strand-long-beach-LBR_1.jpg",
    title: "Diani Beach Safari Combo",
    description: "Ultimate Kenya safari and beach experience.",
    price: 1800,
    currency: "USD",
    duration: "8 days",
    groupSize: "2-8",
    difficulty: "Easy",
    url: "/tours/diani-beach-safari-combo",
    region: "East Africa",
    country: "Kenya",
    highlights: ["Tsavo Safari", "Diani Beach", "Snorkeling", "Diving"],
    included: ["Park fees", "Meals", "Game drives", "Beach resort", "Water sports"],
    excluded: ["Flights", "Tips"],
    itinerary: [
      { day: 1, title: "Safari in Tsavo West", description: "Game drives." },
      { day: 2, title: "Tsavo West", description: "Continue safari." },
      { day: 3, title: "Tsavo West", description: "Final safari day." },
      { day: 4, title: "Tsavo West", description: "Morning drive." },
      { day: 5, title: "Transfer to Diani", description: "Beach arrival." },
      { day: 6, title: "Beach Relaxation", description: "Free day." },
      { day: 7, title: "Snorkeling & Diving", description: "Marine activities." },
      { day: 8, title: "Departure", description: "Fly out." },
    ],
    rating: 4.9,
    reviewCount: 108,
    metaTitle: "Diani Beach Safari Combo - 8 Days | Jae Travel Expeditions",
    metaDescription: "Ultimate Kenya safari and beach experience at Diani Beach.",
    keywords: ["Diani Beach", "Beach Safari", "Kenya Coast", "Safari Beach Combo", "Diani Tours"],
    bookingUrl: "/booking/diani-beach-safari-combo",
    category: "Beach",
    featured: true,
    name: "Diani Beach Safari Combo",
    destinations: ["Tsavo National Park", "Diani Beach"],
    bestTime: ["June-October", "December-March"],
    priceFrom: 1800
  },
  {
    id: "13",
    slug: "serengeti-wildlife-safari",
    image: "/serengeti-day-trip.jpeg",
    title: "Serengeti Wildlife Safari",
    description: "Explore the endless plains of Serengeti and witness incredible wildlife diversity.",
    price: 1800,
    currency: "USD",
    duration: "7 days",
    groupSize: "4-12",
    difficulty: "Moderate",
    url: "/tours/serengeti-wildlife-safari",
    region: "East Africa",
    country: "Tanzania",
    highlights: ["Big Five", "Migration", "Birds", "Plains"],
    included: ["Park fees", "Meals", "Game drives", "Guide", "Accommodation"],
    excluded: ["Flights", "Visa"],
    itinerary: [
      { day: 1, title: "Arrival in Arusha", description: "Welcome and briefing." },
      { day: 2, title: "Serengeti", description: "Fly to Serengeti." },
      { day: 3, title: "Serengeti Full Day", description: "Game drives." },
      { day: 4, title: "Serengeti", description: "Continue exploration." },
      { day: 5, title: "Serengeti", description: "Morning and afternoon drives." },
      { day: 6, title: "Serengeti", description: "Final full day." },
      { day: 7, title: "Departure via Arusha", description: "Fly out." },
    ],
    rating: 4.8,
    reviewCount: 142,
    metaTitle: "Serengeti Wildlife Safari - 7 Days | Jae Travel Expeditions",
    metaDescription: "7-day Serengeti wildlife safari with incredible biodiversity.",
    keywords: ["Serengeti", "Wildlife Safari", "Tanzania", "African Safari", "Big Five Tanzania"],
    bookingUrl: "/booking/serengeti-wildlife-safari",
    category: "Safari",
    featured: false,
    name: "Serengeti Wildlife Safari",
    destinations: ["Serengeti National Park"],
    bestTime: ["June-October", "December-March"],
    priceFrom: 1800
  },
  {
    id: "14",
    slug: "ngorongoro-crater-tour",
    image: "/Ngorongoro-Crater.jpg",
    title: "Ngorongoro Crater Tour",
    description: "Visit the world's largest intact caldera.",
    price: 950,
    currency: "USD",
    duration: "3 days",
    groupSize: "2-8",
    difficulty: "Easy",
    url: "/tours/ngorongoro-crater-tour",
    region: "East Africa",
    country: "Tanzania",
    highlights: ["Black Rhino", "Big Five", "Caldera", "Birds"],
    included: ["Park fees", "Meals", "Crater tour", "Accommodation"],
    excluded: ["Flights", "Tips"],
    itinerary: [
      { day: 1, title: "Arrival & Lodge Check-in", description: "Settle on the rim." },
      { day: 2, title: "Full-Day Crater Tour", description: "Descend and explore." },
      { day: 3, title: "Departure", description: "Morning at leisure and fly out." },
    ],
    rating: 4.9,
    reviewCount: 118,
    metaTitle: "Ngorongoro Crater Tour - 3 Days | Jae Travel Expeditions",
    metaDescription: "Visit the world's largest intact caldera at Ngorongoro.",
    keywords: ["Ngorongoro", "Crater", "Caldera", "Tanzania Safari", "Crater Tour"],
    bookingUrl: "/booking/ngorongoro-crater-tour",
    category: "Safari",
    featured: false,
    name: "Ngorongoro Crater Tour",
    destinations: ["Ngorongoro Conservation Area"],
    bestTime: ["June-September", "January-February"],
    priceFrom: 950
  },
  {
    id: "15",
    slug: "kilimanjaro-climbing-expedition",
    image: "/kilimanjaro-moutain-climbing.jpg",
    title: "Kilimanjaro Climbing",
    description: "Conquer Africa's highest peak.",
    price: 2200,
    currency: "USD",
    duration: "9 days",
    groupSize: "2-10",
    difficulty: "Challenging",
    url: "/tours/kilimanjaro-climbing-expedition",
    region: "East Africa",
    country: "Tanzania",
    highlights: ["Uhuru Peak", "Machame Route", "Alpine Zones", "Summit"],
    included: ["Guide", "Porters", "Meals", "Camping", "Park fees"],
    excluded: ["Flights", "Tips", "Personal gear"],
    itinerary: [
      { day: 1, title: "Arrival & Briefing", description: "Gear check." },
      { day: 2, title: "Machame Gate to Camp 1", description: "Rainforest." },
      { day: 3, title: "Camp 1 to Camp 2", description: "Moorland." },
      { day: 4, title: "Camp 2 to Camp 3", description: "Alpine desert." },
      { day: 5, title: "Camp 3 to Barafu", description: "Acclimatization." },
      { day: 6, title: "Summit Day", description: "Uhuru Peak." },
      { day: 7, title: "Descent", description: "To Mweka Camp." },
      { day: 8, title: "Final Descent", description: "To gate." },
      { day: 9, title: "Departure", description: "Celebration and fly out." },
    ],
    rating: 4.7,
    reviewCount: 76,
    metaTitle: "Kilimanjaro Climbing Expedition - 9 Days | Jae Travel Expeditions",
    metaDescription: "Conquer Africa's highest peak on Mount Kilimanjaro.",
    keywords: ["Kilimanjaro", "Climbing", "Trekking", "Summit", "Machame Route", "Africa Highest Peak"],
    bookingUrl: "/booking/kilimanjaro-climbing-expedition",
    category: "Trekking",
    featured: true,
    name: "Kilimanjaro Climbing Expedition",
    destinations: ["Mount Kilimanjaro"],
    bestTime: ["January-February", "July-October"],
    priceFrom: 2200
  },
  {
    id: "16",
    slug: "tarangire-national-park-safari",
    image: "/boabab-tarangire-national-park.jpg",
    title: "Tarangire Elephant Safari",
    description: "See large herds of elephants.",
    price: 1100,
    currency: "USD",
    duration: "4 days",
    groupSize: "2-8",
    difficulty: "Easy",
    url: "/tours/tarangire-national-park-safari",
    region: "East Africa",
    country: "Tanzania",
    highlights: ["Elephant Herds", "Baobab Trees", "Birdlife", "Seasonal Swamps"],
    included: ["Park fees", "Meals", "Game drives", "Accommodation"],
    excluded: ["Flights", "Tips"],
    itinerary: [
      { day: 1, title: "Arrival & Lodge Check-in", description: "Settle into lodge." },
      { day: 2, title: "Elephant Viewing", description: "Focus on elephant herds." },
      { day: 3, title: "Full Day Safari", description: "Explore Tarangire." },
      { day: 4, title: "Departure", description: "Morning drive and depart." },
    ],
    rating: 4.6,
    reviewCount: 63,
    metaTitle: "Tarangire Elephant Safari - 4 Days | Jae Travel Expeditions",
    metaDescription: "See large herds of elephants in Tarangire National Park.",
    keywords: ["Tarangire", "Elephant Safari", "Tanzania", "Baobab Trees", "Elephant Tour"],
    bookingUrl: "/booking/tarangire-national-park-safari",
    category: "Safari",
    featured: false,
    name: "Tarangire Elephant Safari",
    destinations: ["Tarangire National Park"],
    bestTime: ["June-October", "January-February"],
    priceFrom: 1100
  },
  {
    id: "17",
    slug: "lake-manyara-national-park-safari",
    image: "/Lake Manyara banner.jpg",
    title: "Lake Manyara Tree Climbing Lions",
    description: "Witness unique tree-climbing lions.",
    price: 580,
    currency: "USD",
    duration: "2 days",
    groupSize: "2-8",
    difficulty: "Easy",
    url: "/tours/lake-manyara-national-park-safari",
    region: "East Africa",
    country: "Tanzania",
    highlights: ["Tree Climbing Lions", "Lake Views", "Bird Watching", "Forest"],
    included: ["Park fees", "Meals", "Game drives", "Accommodation"],
    excluded: ["Flights", "Tips"],
    itinerary: [
      { day: 1, title: "Arrival & Afternoon Game Drive", description: "Settle and first drive." },
      { day: 2, title: "Morning Game Drive & Departure", description: "Lion viewing and depart." },
    ],
    rating: 4.4,
    reviewCount: 54,
    metaTitle: "Lake Manyara Tree Climbing Lions Safari - 2 Days | Jae Travel Expeditions",
    metaDescription: "Witness unique tree-climbing lions in Lake Manyara.",
    keywords: ["Lake Manyara", "Tree Climbing Lions", "Tanzania Safari", "Bird Watching", "Lion Tour"],
    bookingUrl: "/booking/lake-manyara-national-park-safari",
    category: "Safari",
    featured: false,
    name: "Lake Manyara Tree Climbing Lions Safari",
    destinations: ["Lake Manyara National Park"],
    bestTime: ["June-October", "January-February"],
    priceFrom: 580
  },
  {
    id: "18",
    slug: "zanzibar-beach-holiday",
    image: "/zanzibar-stone-town-view-min-800x600.jpg",
    title: "Zanzibar Spice Island",
    description: "Explore the spice island paradise.",
    price: 1300,
    currency: "USD",
    duration: "5 days",
    groupSize: "2-10",
    difficulty: "Easy",
    url: "/tours/zanzibar-beach-holiday",
    region: "East Africa",
    country: "Tanzania",
    highlights: ["Stone Town", "Spice Tour", "Beaches", "Dhow Cruise"],
    included: ["Accommodation", "Meals", "Tours", "Transfers"],
    excluded: ["Flights", "Tips"],
    itinerary: [
      { day: 1, title: "Arrival & Stone Town Tour", description: "Historic exploration." },
      { day: 2, title: "Spice Tour", description: "Visit spice farms." },
      { day: 3, title: "Beach Relaxation", description: "Free day." },
      { day: 4, title: "Water Sports", description: "Snorkeling, diving." },
      { day: 5, title: "Departure", description: "Fly out." },
    ],
    rating: 4.8,
    reviewCount: 134,
    metaTitle: "Zanzibar Spice Island Holiday - 5 Days | Jae Travel Expeditions",
    metaDescription: "Explore Zanzibar spice island paradise with beaches and Stone Town.",
    keywords: ["Zanzibar", "Spice Island", "Beach Holiday", "Stone Town", "Tanzania Coast", "Spice Tour"],
    bookingUrl: "/booking/zanzibar-beach-holiday",
    category: "Beach",
    featured: true,
    name: "Zanzibar Spice Island Holiday",
    destinations: ["Zanzibar Island"],
    bestTime: ["June-October", "December-March"],
    priceFrom: 1300
  },
  {
    id: "19",
    slug: "ruaha-national-park-safari",
    image: "/ruaha-national-park-featured.jpg",
    title: "Ruaha National Park",
    description: "Tanzania's largest national park.",
    price: 1450,
    currency: "USD",
    duration: "6 days",
    groupSize: "2-8",
    difficulty: "Moderate",
    url: "/tours/ruaha-national-park-safari",
    region: "East Africa",
    country: "Tanzania",
    highlights: ["Wilderness", "Elephants", "Big Cats", "Remote"],
    included: ["Park fees", "Meals", "Game drives", "Accommodation"],
    excluded: ["Flights", "Tips"],
    itinerary: [
      { day: 1, title: "Arrival & Lodge Check-in", description: "Settle into camp." },
      { day: 2, title: "Game Drives", description: "Explore Ruaha." },
      { day: 3, title: "Full Day Safari", description: "Continue exploration." },
      { day: 4, title: "Wildlife Tracking", description: "Focus on predators." },
      { day: 5, title: "Final Game Drives", description: "Last full day." },
      { day: 6, title: "Departure", description: "Morning drive and depart." },
    ],
    rating: 4.5,
    reviewCount: 47,
    metaTitle: "Ruaha National Park Safari - 6 Days | Jae Travel Expeditions",
    metaDescription: "Explore Tanzania's largest national park at Ruaha.",
    keywords: ["Ruaha", "National Park", "Tanzania Safari", "Wilderness", "Elephant Safari"],
    bookingUrl: "/booking/ruaha-national-park-safari",
    category: "Safari",
    featured: false,
    name: "Ruaha National Park Safari",
    destinations: ["Ruaha National Park"],
    bestTime: ["June-October", "January-February"],
    priceFrom: 1450
  },
  {
    id: "20",
    slug: "selous-game-reserve-safari",
    image: "/SELOUS-GAME-RESERVE.jpg",
    title: "Selous Game Reserve",
    description: "Africa's largest game reserve.",
    price: 1350,
    currency: "USD",
    duration: "5 days",
    groupSize: "2-8",
    difficulty: "Moderate",
    url: "/tours/selous-game-reserve-safari",
    region: "East Africa",
    country: "Tanzania",
    highlights: ["Boat Safari", "Walking Safari", "Wild Dogs", "Rufiji River"],
    included: ["Park fees", "Meals", "Game drives", "Boat safari", "Accommodation"],
    excluded: ["Flights", "Tips"],
    itinerary: [
      { day: 1, title: "Arrival & Lodge Check-in", description: "Settle into camp." },
      { day: 2, title: "Game Drives", description: "Land-based safari." },
      { day: 3, title: "Boat Safari", description: "Rufiji River exploration." },
      { day: 4, title: "Walking Safari", description: "Guided bush walk." },
      { day: 5, title: "Departure", description: "Final activity and depart." },
    ],
    rating: 4.7,
    reviewCount: 59,
    metaTitle: "Selous Game Reserve Safari - 5 Days | Jae Travel Expeditions",
    metaDescription: "Explore Africa's largest game reserve at Selous.",
    keywords: ["Selous", "Game Reserve", "Tanzania", "Boat Safari", "Walking Safari"],
    bookingUrl: "/booking/selous-game-reserve-safari",
    category: "Safari",
    featured: false,
    name: "Selous Game Reserve Safari",
    destinations: ["Selous Game Reserve"],
    bestTime: ["June-October", "January-February"],
    priceFrom: 1350
  },
  {
    id: "21",
    slug: "mikumi-national-park",
    image: "/Mikumi2017.jpg",
    title: "Mikumi National Park",
    description: "Accessible wildlife viewing.",
    price: 750,
    currency: "USD",
    duration: "3 days",
    groupSize: "2-8",
    difficulty: "Easy",
    url: "/tours/mikumi-national-park",
    region: "East Africa",
    country: "Tanzania",
    highlights: ["Accessible Location", "Wildlife Diversity", "Bird Watching", "Family Friendly"],
    included: ["Park fees", "Meals", "Game drives", "Accommodation"],
    excluded: ["Flights", "Tips"],
    itinerary: [
      { day: 1, title: "Arrival & Afternoon Game Drive", description: "Settle and first drive." },
      { day: 2, title: "Full-Day Game Drive", description: "Explore Mikumi." },
      { day: 3, title: "Departure", description: "Morning drive and depart." },
    ],
    rating: 4.3,
    reviewCount: 42,
    metaTitle: "Mikumi National Park Safari - 3 Days | Jae Travel Expeditions",
    metaDescription: "Accessible wildlife viewing in Mikumi National Park.",
    keywords: ["Mikumi", "National Park", "Wildlife Viewing", "Tanzania", "Safari"],
    bookingUrl: "/booking/mikumi-national-park",
    category: "Safari",
    featured: false,
    name: "Mikumi National Park Safari",
    destinations: ["Mikumi National Park"],
    bestTime: ["June-October", "January-February"],
    priceFrom: 750
  },
  {
    id: "22",
    slug: "arusha-cultural-tour",
    image: "/Cultural-Heritage-Centre-Arusha-Tanzania.jpg",
    title: "Arusha Cultural Tour",
    description: "Experience local Tanzanian culture.",
    price: 420,
    currency: "USD",
    duration: "2 days",
    groupSize: "2-10",
    difficulty: "Easy",
    url: "/tours/arusha-cultural-tour",
    region: "East Africa",
    country: "Tanzania",
    highlights: ["Cultural Center", "Maasai Village", "Local Markets", "Traditional Crafts"],
    included: ["Guide", "Meals", "Cultural activities", "Accommodation"],
    excluded: ["Flights", "Tips"],
    itinerary: [
      { day: 1, title: "City Tour & Cultural Center", description: "Explore Arusha and cultural sites." },
      { day: 2, title: "Maasai Village Visit & Departure", description: "Traditional village experience." },
    ],
    rating: 4.2,
    reviewCount: 38,
    metaTitle: "Arusha Cultural Tour - 2 Days | Jae Travel Expeditions",
    metaDescription: "Experience local Tanzanian culture in Arusha.",
    keywords: ["Arusha", "Cultural Tour", "Tanzania Culture", "Maasai Village", "Cultural Experience"],
    bookingUrl: "/booking/arusha-cultural-tour",
    category: "Cultural",
    featured: false,
    name: "Arusha Cultural Tour",
    destinations: ["Arusha"],
    bestTime: ["Year-round"],
    priceFrom: 420
  },
  {
    id: "23",
    slug: "katavi-national-park-safari",
    image: "/Katavi-National-Park-600x400.png",
    title: "Katavi National Park",
    description: "Remote wilderness experience.",
    price: 1600,
    currency: "USD",
    duration: "4 days",
    groupSize: "2-6",
    difficulty: "Moderate",
    url: "/tours/katavi-national-park-safari",
    region: "East Africa",
    country: "Tanzania",
    highlights: ["Remote Wilderness", "Hippo Pools", "Large Herds", "Solitude"],
    included: ["Park fees", "Meals", "Game drives", "Accommodation"],
    excluded: ["Flights", "Tips"],
    itinerary: [
      { day: 1, title: "Arrival & Lodge Check-in", description: "Settle into remote camp." },
      { day: 2, title: "Game Drives in Wilderness", description: "Explore remote areas." },
      { day: 3, title: "Hippo Pool Visits", description: "Wildlife concentration areas." },
      { day: 4, title: "Departure", description: "Final drive and depart." },
    ],
    rating: 4.6,
    reviewCount: 31,
    metaTitle: "Katavi National Park Safari - 4 Days | Jae Travel Expeditions",
    metaDescription: "Remote wilderness experience in Katavi National Park.",
    keywords: ["Katavi", "National Park", "Wilderness", "Remote Safari", "Tanzania"],
    bookingUrl: "/booking/katavi-national-park-safari",
    category: "Safari",
    featured: false,
    name: "Katavi National Park Safari",
    destinations: ["Katavi National Park"],
    bestTime: ["June-October"],
    priceFrom: 1600
  },
  {
    id: "24",
    slug: "mahale-mountains-national-park-chimpanzee-trekking",
    image: "/Chimp-Group-Mahale-Mountain-JEP_8612.jpg",
    title: "Mahale Chimpanzee Trek",
    description: "Trek with wild chimpanzees.",
    price: 2100,
    currency: "USD",
    duration: "6 days",
    groupSize: "2-6",
    difficulty: "Challenging",
    url: "/tours/mahale-mountains-national-park-chimpanzee-trekking",
    region: "East Africa",
    country: "Tanzania",
    highlights: ["Chimpanzee Trekking", "Lake Tanganyika", "Forest Hiking", "Primate Research"],
    included: ["Park fees", "Guide", "Accommodation", "Meals", "Chimp permits"],
    excluded: ["Flights", "Tips"],
    itinerary: [
      { day: 1, title: "Arrival at Lake Tanganyika", description: "Settle into lakeside camp." },
      { day: 2, title: "Chimpanzee Trekking", description: "First trekking experience." },
      { day: 3, title: "Forest Exploration", description: "Deep forest hiking." },
      { day: 4, title: "Chimpanzee Observation", description: "Behavioral study." },
      { day: 5, title: "Lake Activities", description: "Swimming and relaxation." },
      { day: 6, title: "Departure", description: "Fly out from airstrip." },
    ],
    rating: 4.9,
    reviewCount: 44,
    metaTitle: "Mahale Chimpanzee Trek - 6 Days | Jae Travel Expeditions",
    metaDescription: "Trek with wild chimpanzees in Mahale Mountains.",
    keywords: ["Mahale", "Chimpanzee Trek", "Tanzania", "Lake Tanganyika", "Primate Trekking"],
    bookingUrl: "/booking/mahale-mountains-national-park-chimpanzee-trekking",
    category: "Trekking",
    featured: false,
    name: "Mahale Chimpanzee Trek",
    destinations: ["Mahale Mountains National Park"],
    bestTime: ["May-October"],
    priceFrom: 2100
  },
  {
    id: "25",
    slug: "pemba-island-diving",
    image: "/Pemba-Island-15.jpg",
    title: "Pemba Island Diving",
    description: "World-class diving experience.",
    price: 980,
    currency: "USD",
    duration: "4 days",
    groupSize: "2-8",
    difficulty: "Moderate",
    url: "/tours/pemba-island-diving",
    region: "East Africa",
    country: "Tanzania",
    highlights: ["Coral Reefs", "Marine Life", "Clear Waters", "Diving Sites"],
    included: ["Diving equipment", "Guide", "Accommodation", "Meals", "Dive trips"],
    excluded: ["Flights", "Tips", "Diving certification"],
    itinerary: [
      { day: 1, title: "Arrival & Orientation", description: "Dive briefing and equipment check." },
      { day: 2, title: "Diving Expeditions", description: "Multiple dive sites." },
      { day: 3, title: "Advanced Diving", description: "Deep dives and wrecks." },
      { day: 4, title: "Departure", description: "Final dive and depart." },
    ],
    rating: 4.5,
    reviewCount: 56,
    metaTitle: "Pemba Island Diving - 4 Days | Jae Travel Expeditions",
    metaDescription: "World-class diving in Pemba Island.",
    keywords: ["Pemba Island", "Diving", "Scuba Diving", "Tanzania", "Coral Reefs"],
    bookingUrl: "/booking/pemba-island-diving",
    category: "Adventure",
    featured: false,
    name: "Pemba Island Diving",
    destinations: ["Pemba Island"],
    bestTime: ["June-October", "December-March"],
    priceFrom: 980
  },
  {
    id: "26",
    slug: "stone-town-heritage-tour",
    image: "/31719088_tourists-on-a-typical-narrow-street-in-stone-town-zanzibar-e1713023620250.jpg",
    title: "Stone Town Heritage Tour",
    description: "Explore UNESCO World Heritage site.",
    price: 350,
    currency: "USD",
    duration: "2 days",
    groupSize: "2-12",
    difficulty: "Easy",
    url: "/tours/stone-town-heritage-tour",
    region: "East Africa",
    country: "Tanzania",
    highlights: ["UNESCO Site", "Historic Architecture", "Local Markets", "Cultural History"],
    included: ["Guide", "Meals", "Entrance fees", "Accommodation"],
    excluded: ["Flights", "Tips"],
    itinerary: [
      { day: 1, title: "Guided Walking Tour", description: "Explore Stone Town history." },
      { day: 2, title: "Spice Tour & Departure", description: "Cultural experiences and depart." },
    ],
    rating: 4.4,
    reviewCount: 72,
    metaTitle: "Stone Town Heritage Tour - 2 Days | Jae Travel Expeditions",
    metaDescription: "Explore UNESCO World Heritage site in Stone Town.",
    keywords: ["Stone Town", "Heritage Tour", "UNESCO", "Zanzibar", "Cultural Tour"],
    bookingUrl: "/booking/stone-town-heritage-tour",
    category: "Cultural",
    featured: false,
    name: "Stone Town Heritage Tour",
    destinations: ["Stone Town, Zanzibar"],
    bestTime: ["Year-round"],
    priceFrom: 350
  },
  {
    id: "27",
    slug: "northern-circuit-safari",
    image: "/Game-Drive-north-of-Serengeti-National-Park.jpg",
    title: "Northern Circuit Safari",
    description: "Complete northern Tanzania experience.",
    price: 2800,
    currency: "USD",
    duration: "10 days",
    groupSize: "4-12",
    difficulty: "Moderate",
    url: "/tours/northern-circuit-safari",
    region: "East Africa",
    country: "Tanzania",
    highlights: ["Multiple Parks", "Big Five", "Cultural Experiences", "Comprehensive Safari"],
    included: ["All park fees", "Meals", "Game drives", "Guide", "Accommodation"],
    excluded: ["Flights", "Visa", "Tips"],
    itinerary: [
      { day: 1, title: "Arrival in Arusha", description: "Welcome and briefing." },
      { day: 2, title: "Tarangire National Park", description: "Elephants and baobabs." },
      { day: 3, title: "Lake Manyara", description: "Tree-climbing lions." },
      { day: 4, title: "Serengeti", description: "Migration tracking." },
      { day: 5, title: "Serengeti Full Day", description: "Big cats and plains." },
      { day: 6, title: "Serengeti", description: "Wildlife exploration." },
      { day: 7, title: "Ngorongoro Crater", description: "Crater descent." },
      { day: 8, title: "Ngorongoro", description: "Full day in crater." },
      { day: 9, title: "Cultural Visits", description: "Local communities." },
      { day: 10, title: "Departure", description: "Fly out from Arusha." },
    ],
    rating: 4.9,
    reviewCount: 87,
    metaTitle: "Northern Circuit Safari - 10 Days | Jae Travel Expeditions",
    metaDescription: "Complete northern Tanzania safari circuit experience.",
    keywords: ["Northern Circuit", "Tanzania Safari", "Comprehensive Safari", "Multi-Park Safari"],
    bookingUrl: "/booking/northern-circuit-safari",
    category: "Safari",
    featured: true,
    name: "Northern Circuit Safari",
    destinations: ["Tarangire", "Lake Manyara", "Serengeti", "Ngorongoro"],
    bestTime: ["June-October", "December-March"],
    priceFrom: 2800
  },
  {
    id: "28",
    slug: "gorilla-trekking-experience",
    image: "/gorilla-trekking-experience-13.jpg",
    title: "Rwanda Gorilla Trekking Experience",
    description: "Get up close with mountain gorillas in Volcanoes National Park, Rwanda.",
    price: 2500,
    currency: "USD",
    duration: "3 days",
    groupSize: "1-8",
    difficulty: "Challenging",
    url: "/tours/gorilla-trekking-experience",
    region: "East Africa",
    country: "Rwanda",
    highlights: ["Mountain Gorillas", "Volcanoes", "Rainforest", "Conservation"],
    included: ["Gorilla permit", "Guide", "Accommodation", "Meals"],
    excluded: ["Flights", "Visa", "Tips"],
    itinerary: [
      { day: 1, title: "Arrival in Kigali", description: "Transfer to Volcanoes region." },
      { day: 2, title: "Gorilla Trekking", description: "Full day with gorillas." },
      { day: 3, title: "Cultural Tour & Departure", description: "Local experiences and depart." },
    ],
    rating: 5.0,
    reviewCount: 98,
    metaTitle: "Rwanda Gorilla Trekking Experience - 3 Days | Jae Travel Expeditions",
    metaDescription: "Get up close with mountain gorillas in Volcanoes National Park.",
    keywords: ["Gorilla Trekking", "Rwanda", "Mountain Gorillas", "Volcanoes National Park", "Gorilla Safari"],
    bookingUrl: "/booking/gorilla-trekking-experience",
    category: "Trekking",
    featured: true,
    name: "Rwanda Gorilla Trekking Experience",
    destinations: ["Volcanoes National Park"],
    bestTime: ["June-September", "December-February"],
    priceFrom: 2500
  },
  {
    id: "29",
    slug: "nyungwe-forest-canopy-walk",
    image: "/nyungwe-forests.jpg",
    title: "Nyungwe Forest Canopy Walk",
    description: "Walk among the treetops.",
    price: 450,
    currency: "USD",
    duration: "2 days",
    groupSize: "2-10",
    difficulty: "Moderate",
    url: "/tours/nyungwe-forest-canopy-walk",
    region: "East Africa",
    country: "Rwanda",
    highlights: ["Canopy Walkway", "Chimpanzee Tracking", "Forest Biodiversity", "Bird Watching"],
    included: ["Park fees", "Guide", "Accommodation", "Meals"],
    excluded: ["Flights", "Tips"],
    itinerary: [
      { day: 1, title: "Arrival & Forest Orientation", description: "Settle and forest briefing." },
      { day: 2, title: "Canopy Walk & Chimpanzee Tracking", description: "Treetop walk and primate tracking." },
    ],
    rating: 4.6,
    reviewCount: 51,
    metaTitle: "Nyungwe Forest Canopy Walk - 2 Days | Jae Travel Expeditions",
    metaDescription: "Walk among the treetops in Nyungwe Forest.",
    keywords: ["Nyungwe Forest", "Canopy Walk", "Rwanda", "Chimpanzee Tracking", "Forest Tour"],
    bookingUrl: "/booking/nyungwe-forest-canopy-walk",
    category: "Adventure",
    featured: false,
    name: "Nyungwe Forest Canopy Walk",
    destinations: ["Nyungwe Forest National Park"],
    bestTime: ["June-September", "December-February"],
    priceFrom: 450
  },
  {
    id: "30",
    slug: "lake-kivu-relaxation",
    image: "/Lake-Kivu-Islands.jpg",
    title: "Lake Kivu Relaxation",
    description: "Relax by Africa's great lake.",
    price: 380,
    currency: "USD",
    duration: "3 days",
    groupSize: "2-8",
    difficulty: "Easy",
    url: "/tours/lake-kivu-relaxation",
    region: "East Africa",
    country: "Rwanda",
    highlights: ["Lake Views", "Island Hopping", "Beach Relaxation", "Sunset Cruises"],
    included: ["Accommodation", "Meals", "Boat tours", "Guide"],
    excluded: ["Flights", "Tips"],
    itinerary: [
      { day: 1, title: "Arrival & Beach Relaxation", description: "Settle into lakeside resort." },
      { day: 2, title: "Boat Tour & Island Visits", description: "Explore lake islands." },
      { day: 3, title: "Departure", description: "Morning relaxation and depart." },
    ],
    rating: 4.4,
    reviewCount: 43,
    metaTitle: "Lake Kivu Relaxation - 3 Days | Jae Travel Expeditions",
    metaDescription: "Relax by Africa's great lake at Lake Kivu.",
    keywords: ["Lake Kivu", "Relaxation", "Rwanda", "Beach Holiday", "Lake Tours"],
    bookingUrl: "/booking/lake-kivu-relaxation",
    category: "Beach",
    featured: false,
    name: "Lake Kivu Relaxation",
    destinations: ["Lake Kivu"],
    bestTime: ["June-September", "December-February"],
    priceFrom: 380
  },
  {
    id: "31",
    slug: "akagera-national-park-safari",
    image: "/Akagera-national-park-1-750x450.jpg",
    title: "Akagera National Park",
    description: "Rwanda's only savanna park.",
    price: 520,
    currency: "USD",
    duration: "2 days",
    groupSize: "2-8",
    difficulty: "Easy",
    url: "/tours/akagera-national-park-safari",
    region: "East Africa",
    country: "Rwanda",
    highlights: ["Big Five", "Lake Ihema", "Boat Safari", "Wildlife Diversity"],
    included: ["Park fees", "Meals", "Game drives", "Boat safari", "Accommodation"],
    excluded: ["Flights", "Tips"],
    itinerary: [
      { day: 1, title: "Arrival & Afternoon Game Drive", description: "Settle and first drive." },
      { day: 2, title: "Full-Day Game Drive & Boat Safari", description: "Land and water exploration." },
    ],
    rating: 4.5,
    reviewCount: 48,
    metaTitle: "Akagera National Park Safari - 2 Days | Jae Travel Expeditions",
    metaDescription: "Explore Rwanda's only savanna park at Akagera.",
    keywords: ["Akagera", "National Park", "Rwanda Safari", "Big Five", "Safari Tour"],
    bookingUrl: "/booking/akagera-national-park-safari",
    category: "Safari",
    featured: false,
    name: "Akagera National Park Safari",
    destinations: ["Akagera National Park"],
    bestTime: ["June-September", "December-February"],
    priceFrom: 520
  },
  {
    id: "32",
    slug: "kigali-city-tour",
    image: "/kigali-photo-600x300.jpg",
    title: "Kigali City Tour",
    description: "Explore the clean city of Kigali.",
    price: 150,
    currency: "USD",
    duration: "1 day",
    groupSize: "1-15",
    difficulty: "Easy",
    url: "/tours/kigali-city-tour",
    region: "East Africa",
    country: "Rwanda",
    highlights: ["Genocide Memorial", "Local Markets", "City Views", "Cultural Sites"],
    included: ["Guide", "Transport", "Entrance fees", "Lunch"],
    excluded: ["Tips"],
    itinerary: [
      { day: 1, title: "Full-Day City Tour", description: "Comprehensive Kigali exploration." },
    ],
    rating: 4.3,
    reviewCount: 67,
    metaTitle: "Kigali City Tour - 1 Day | Jae Travel Expeditions",
    metaDescription: "Explore the clean city of Kigali.",
    keywords: ["Kigali", "City Tour", "Rwanda", "Genocide Memorial", "City Tours"],
    bookingUrl: "/booking/kigali-city-tour",
    category: "Cultural",
    featured: false,
    name: "Kigali City Tour",
    destinations: ["Kigali"],
    bestTime: ["Year-round"],
    priceFrom: 150
  },
  {
    id: "33",
    slug: "golden-monkey-tracking",
    image: "/golden-monkey-trekking.jpg",
    title: "Golden Monkey Tracking",
    description: "Track rare golden monkeys.",
    price: 680,
    currency: "USD",
    duration: "2 days",
    groupSize: "2-8",
    difficulty: "Moderate",
    url: "/tours/golden-monkey-tracking",
    region: "East Africa",
    country: "Rwanda",
    highlights: ["Golden Monkeys", "Bamboo Forest", "Primate Behavior", "Photography"],
    included: ["Park fees", "Guide", "Accommodation", "Meals", "Tracking permit"],
    excluded: ["Flights", "Tips"],
    itinerary: [
      { day: 1, title: "Arrival & Briefing", description: "Settle and tracking preparation." },
      { day: 2, title: "Golden Monkey Tracking & Cultural Visit", description: "Primate tracking and local culture." },
    ],
    rating: 4.7,
    reviewCount: 39,
    metaTitle: "Golden Monkey Tracking - 2 Days | Jae Travel Expeditions",
    metaDescription: "Track rare golden monkeys in Rwanda.",
    keywords: ["Golden Monkey", "Tracking", "Rwanda", "Primate Trekking", "Monkey Safari"],
    bookingUrl: "/booking/golden-monkey-tracking",
    category: "Trekking",
    featured: false,
    name: "Golden Monkey Tracking",
    destinations: ["Volcanoes National Park"],
    bestTime: ["June-September", "December-February"],
    priceFrom: 680
  },
  {
    id: "34",
    slug: "bwindi-gorilla-trekking",
    image: "/Magical-encounters-with-the-mountain-gorillas-of-Bwindi.jpg",
    title: "Bwindi Gorilla Trekking",
    description: "Trek mountain gorillas in Bwindi Impenetrable Forest, Uganda.",
    price: 2200,
    currency: "USD",
    duration: "4 days",
    groupSize: "1-8",
    difficulty: "Challenging",
    url: "/tours/bwindi-gorilla-trekking",
    region: "East Africa",
    country: "Uganda",
    highlights: ["Mountain Gorillas", "Rainforest", "Batwa Culture", "Conservation"],
    included: ["Gorilla permit", "Guide", "Accommodation", "Meals", "Transfers"],
    excluded: ["Flights", "Visa", "Tips"],
    itinerary: [
      { day: 1, title: "Arrival & Lodge Check-in", description: "Transfer to Bwindi and settle." },
      { day: 2, title: "Gorilla Trekking", description: "Full day with gorillas." },
      { day: 3, title: "Cultural Experiences", description: "Batwa community visits." },
      { day: 4, title: "Departure", description: "Morning activities and depart." },
    ],
    rating: 4.9,
    reviewCount: 87,
    metaTitle: "Bwindi Gorilla Trekking - 4 Days | Jae Travel Expeditions",
    metaDescription: "Trek mountain gorillas in Bwindi Impenetrable Forest.",
    keywords: ["Bwindi", "Gorilla Trekking", "Uganda", "Mountain Gorillas", "Gorilla Safari"],
    bookingUrl: "/booking/bwindi-gorilla-trekking",
    category: "Trekking",
    featured: true,
    name: "Bwindi Gorilla Trekking",
    destinations: ["Bwindi Impenetrable National Park"],
    bestTime: ["June-September", "December-February"],
    priceFrom: 2200
  },
  {
    id: "35",
    slug: "queen-elizabeth-national-park-safari",
    image: "/Queen-Elizabeth-National-Park.jpg",
    title: "Queen Elizabeth Safari",
    description: "Diverse wildlife in scenic landscapes at Queen Elizabeth National Park.",
    price: 1150,
    currency: "USD",
    duration: "5 days",
    groupSize: "2-8",
    difficulty: "Moderate",
    url: "/tours/queen-elizabeth-national-park-safari",
    region: "East Africa",
    country: "Uganda",
    highlights: ["Tree Climbing Lions", "Kazinga Channel", "Crater Lakes", "Bird Watching"],
    included: ["Park fees", "Meals", "Game drives", "Boat safari", "Accommodation"],
    excluded: ["Flights", "Tips"],
    itinerary: [
      { day: 1, title: "Arrival", description: "Settle into lodge." },
      { day: 2, title: "Game Drives", description: "Explore park wildlife." },
      { day: 3, title: "Boat Safari", description: "Kazinga Channel exploration." },
      { day: 4, title: "Crater Lakes", description: "Scenic landscape tours." },
      { day: 5, title: "Departure", description: "Final activities and depart." },
    ],
    rating: 4.6,
    reviewCount: 76,
    metaTitle: "Queen Elizabeth Safari - 5 Days | Jae Travel Expeditions",
    metaDescription: "Diverse wildlife in scenic landscapes at Queen Elizabeth National Park.",
    keywords: ["Queen Elizabeth", "National Park", "Uganda Safari", "Wildlife", "Kazinga Channel"],
    bookingUrl: "/booking/queen-elizabeth-national-park-safari",
    category: "Safari",
    featured: false,
    name: "Queen Elizabeth Safari",
    destinations: ["Queen Elizabeth National Park"],
    bestTime: ["June-October", "December-February"],
    priceFrom: 1150
  },
  {
    id: "36",
    slug: "murchison-falls-national-park-safari",
    image: "/murchison-falls.webp",
    title: "Murchison Falls Adventure",
    description: "Witness the powerful Murchison Falls.",
    price: 980,
    currency: "USD",
    duration: "4 days",
    groupSize: "2-8",
    difficulty: "Moderate",
    url: "/tours/murchison-falls-national-park-safari",
    region: "East Africa",
    country: "Uganda",
    highlights: ["Murchison Falls", "Nile River", "Game Drives", "Boat Safaris"],
    included: ["Park fees", "Meals", "Game drives", "Boat safari", "Accommodation"],
    excluded: ["Flights", "Tips"],
    itinerary: [
      { day: 1, title: "Arrival & Lodge Check-in", description: "Settle into falls area." },
      { day: 2, title: "Game Drives", description: "Northern bank exploration." },
      { day: 3, title: "Boat Safari to Falls", description: "Nile River journey." },
      { day: 4, title: "Departure", description: "Final views and depart." },
    ],
    rating: 4.7,
    reviewCount: 64,
    metaTitle: "Murchison Falls Adventure - 4 Days | Jae Travel Expeditions",
    metaDescription: "Witness the powerful Murchison Falls in Uganda.",
    keywords: ["Murchison Falls", "Adventure", "Uganda", "Waterfall Safari", "Game Drive"],
    bookingUrl: "/booking/murchison-falls-national-park-safari",
    category: "Adventure",
    featured: false,
    name: "Murchison Falls Adventure",
    destinations: ["Murchison Falls National Park"],
    bestTime: ["June-October", "December-February"],
    priceFrom: 980
  },
  {
    id: "37",
    slug: "kibale-national-park-chimpanzee-trekking",
    image: "/kibale-national-park-chimpanzees-uganda-590x390.jpg",
    title: "Kibale Chimpanzee Tracking",
    description: "Track our closest relatives.",
    price: 750,
    currency: "USD",
    duration: "3 days",
    groupSize: "2-8",
    difficulty: "Moderate",
    url: "/tours/kibale-national-park-chimpanzee-trekking",
    region: "East Africa",
    country: "Uganda",
    highlights: ["Chimpanzee Tracking", "Primate Diversity", "Forest Walks", "Bird Watching"],
    included: ["Park fees", "Guide", "Accommodation", "Meals", "Chimp permit"],
    excluded: ["Flights", "Tips"],
    itinerary: [
      { day: 1, title: "Arrival & Lodge Check-in", description: "Settle into forest area." },
      { day: 2, title: "Chimpanzee Tracking", description: "Full day primate experience." },
      { day: 3, title: "Bigodi Wetland Walk & Departure", description: "Ecosystem exploration and depart." },
    ],
    rating: 4.5,
    reviewCount: 58,
    metaTitle: "Kibale Chimpanzee Tracking - 3 Days | Jae Travel Expeditions",
    metaDescription: "Track our closest relatives in Kibale National Park.",
    keywords: ["Kibale", "Chimpanzee Tracking", "Uganda", "Primate Safari", "Chimp Trek"],
    bookingUrl: "/booking/kibale-national-park-chimpanzee-trekking",
    category: "Trekking",
    featured: false,
    name: "Kibale Chimpanzee Tracking",
    destinations: ["Kibale National Park"],
    bestTime: ["June-October", "December-February"],
    priceFrom: 750
  },
  {
    id: "38",
    slug: "lake-mburo-national-park-safari",
    image: "/lake-mburo-national-park.jpg",
    title: "Lake Mburo National Park",
    description: "Compact park with diverse wildlife.",
    price: 420,
    currency: "USD",
    duration: "2 days",
    groupSize: "2-8",
    difficulty: "Easy",
    url: "/tours/lake-mburo-national-park-safari",
    region: "East Africa",
    country: "Uganda",
    highlights: ["Lake Views", "Zebra Herds", "Boat Safari", "Walking Safari"],
    included: ["Park fees", "Meals", "Game drives", "Boat safari", "Accommodation"],
    excluded: ["Flights", "Tips"],
    itinerary: [
      { day: 1, title: "Arrival & Afternoon Game Drive", description: "Settle and first drive." },
      { day: 2, title: "Morning Game Drive & Boat Safari", description: "Land and water exploration." },
    ],
    rating: 4.3,
    reviewCount: 41,
    metaTitle: "Lake Mburo National Park Safari - 2 Days | Jae Travel Expeditions",
    metaDescription: "Compact park with diverse wildlife at Lake Mburo.",
    keywords: ["Lake Mburo", "National Park", "Uganda Safari", "Boat Safari", "Wildlife Tour"],
    bookingUrl: "/booking/lake-mburo-national-park-safari",
    category: "Safari",
    featured: false,
    name: "Lake Mburo National Park Safari",
    destinations: ["Lake Mburo National Park"],
    bestTime: ["June-October", "December-February"],
    priceFrom: 420
  },
  {
    id: "39",
    slug: "rwenzori-mountains-hiking",
    image: "/Rwenzori-Mountains-03_1600p.jpg",
    title: "Rwenzori Mountains Hiking",
    description: "Hike the Mountains of the Moon.",
    price: 1800,
    currency: "USD",
    duration: "7 days",
    groupSize: "2-6",
    difficulty: "Challenging",
    url: "/tours/rwenzori-mountains-hiking",
    region: "East Africa",
    country: "Uganda",
    highlights: ["Mountains of the Moon", "Alpine Vegetation", "Glaciers", "Summit Views"],
    included: ["Guide", "Porters", "Meals", "Camping gear", "Park fees"],
    excluded: ["Flights", "Tips", "Personal gear"],
    itinerary: [
      { day: 1, title: "Arrival & Briefing", description: "Gear check and preparation." },
      { day: 2, title: "Start Ascent", description: "Begin mountain climb." },
      { day: 3, title: "Alpine Zone", description: "Higher elevation hiking." },
      { day: 4, title: "Glacier Views", description: "Mountain scenery." },
      { day: 5, title: "Summit Approach", description: "High altitude camping." },
      { day: 6, title: "Descent", description: "Return journey." },
      { day: 7, title: "Departure", description: "Final descent and depart." },
    ],
    rating: 4.8,
    reviewCount: 35,
    metaTitle: "Rwenzori Mountains Hiking - 7 Days | Jae Travel Expeditions",
    metaDescription: "Hike the Mountains of the Moon in Rwenzori Mountains.",
    keywords: ["Rwenzori", "Mountains", "Hiking", "Uganda", "Mountains of the Moon"],
    bookingUrl: "/booking/rwenzori-mountains-hiking",
    category: "Trekking",
    featured: false,
    name: "Rwenzori Mountains Hiking",
    destinations: ["Rwenzori Mountains National Park"],
    bestTime: ["January-February", "July-August"],
    priceFrom: 1800
  },
  {
    id: "40",
    slug: "jinja-adventure-tour",
    image: "/6-days-gorilla-tracking-and-rafting-jinja.jpg",
    title: "Jinja White Water Rafting",
    description: "Adventure at the source of the Nile.",
    price: 350,
    currency: "USD",
    duration: "2 days",
    groupSize: "2-12",
    difficulty: "Moderate",
    url: "/tours/jinja-adventure-tour",
    region: "East Africa",
    country: "Uganda",
    highlights: ["White Water Rafting", "Nile Source", "Adventure Sports", "River Activities"],
    included: ["Rafting equipment", "Guide", "Meals", "Accommodation"],
    excluded: ["Flights", "Tips"],
    itinerary: [
      { day: 1, title: "Arrival & Nile Source Visit", description: "Explore Nile origin point." },
      { day: 2, title: "White Water Rafting & Departure", description: "Adventure rafting and depart." },
    ],
    rating: 4.6,
    reviewCount: 92,
    metaTitle: "Jinja White Water Rafting - 2 Days | Jae Travel Expeditions",
    metaDescription: "Adventure at the source of the Nile in Jinja.",
    keywords: ["Jinja", "White Water Rafting", "Nile River", "Adventure", "Uganda"],
    bookingUrl: "/booking/jinja-adventure-tour",
    category: "Adventure",
    featured: false,
    name: "Jinja White Water Rafting",
    destinations: ["Jinja"],
    bestTime: ["June-October", "December-February"],
    priceFrom: 350
  },
  {
    id: "41",
    slug: "lake-bunyonyi-relaxation-tour",
    image: "/lake_bunyonyi__uganda-the-pearl-of-africa.webp",
    title: "Lake Bunyonyi Relaxation",
    description: "Relax by Uganda's deepest lake.",
    price: 450,
    currency: "USD",
    duration: "3 days",
    groupSize: "2-8",
    difficulty: "Easy",
    url: "/tours/lake-bunyonyi-relaxation-tour",
    region: "East Africa",
    country: "Uganda",
    highlights: ["Lake Views", "Island Hopping", "Canoeing", "Relaxation"],
    included: ["Accommodation", "Meals", "Boat tours", "Guide"],
    excluded: ["Flights", "Tips"],
    itinerary: [
      { day: 1, title: "Arrival & Lake Orientation", description: "Settle into lakeside resort." },
      { day: 2, title: "Island Hopping & Canoeing", description: "Explore lake islands." },
      { day: 3, title: "Departure", description: "Morning relaxation and depart." },
    ],
    rating: 4.4,
    reviewCount: 47,
    metaTitle: "Lake Bunyonyi Relaxation - 3 Days | Jae Travel Expeditions",
    metaDescription: "Relax by Uganda's deepest lake at Lake Bunyonyi.",
    keywords: ["Lake Bunyonyi", "Relaxation", "Uganda", "Island Hopping", "Lake Tours"],
    bookingUrl: "/booking/lake-bunyonyi-relaxation-tour",
    category: "Beach",
    featured: false,
    name: "Lake Bunyonyi Relaxation",
    destinations: ["Lake Bunyonyi"],
    bestTime: ["June-October", "December-February"],
    priceFrom: 450
  },
  {
    id: "42",
    slug: "ssese-islands-beach-holiday",
    image: "/Travel-to-Ssese-islands.jpg",
    title: "Ssese Islands Beach Holiday",
    description: "Beach paradise on Lake Victoria.",
    price: 650,
    currency: "USD",
    duration: "4 days",
    groupSize: "2-8",
    difficulty: "Easy",
    url: "/tours/ssese-islands-beach-holiday",
    region: "East Africa",
    country: "Uganda",
    highlights: ["Lake Victoria", "Beach Relaxation", "Water Sports", "Island Life"],
    included: ["Accommodation", "Meals", "Water sports", "Boat transfers"],
    excluded: ["Flights", "Tips"],
    itinerary: [
      { day: 1, title: "Arrival & Beach Relaxation", description: "Settle into island resort." },
      { day: 2, title: "Water Sports", description: "Swimming, kayaking, fishing." },
      { day: 3, title: "Island Exploration", description: "Explore different islands." },
      { day: 4, title: "Departure", description: "Morning activities and depart." },
    ],
    rating: 4.5,
    reviewCount: 53,
    metaTitle: "Ssese Islands Beach Holiday - 4 Days | Jae Travel Expeditions",
    metaDescription: "Beach paradise on Lake Victoria at Ssese Islands.",
    keywords: ["Ssese Islands", "Beach Holiday", "Lake Victoria", "Uganda", "Beach Tour"],
    bookingUrl: "/booking/ssese-islands-beach-holiday",
    category: "Beach",
    featured: false,
    name: "Ssese Islands Beach Holiday",
    destinations: ["Ssese Islands"],
    bestTime: ["June-October", "December-March"],
    priceFrom: 650
  },
  {
    id: "43",
    slug: "lake-naivasha-boat-safari",
    image: "/Lake-Naivasha-National-Park-750x450.jpg",
    title: "Lake Naivasha Boat Safari",
    description: "Boat safari on freshwater Lake Naivasha with hippos, birds, and Crescent Island walking safari.",
    price: 150,
    currency: "USD",
    duration: "1 day",
    groupSize: "2-12",
    difficulty: "Easy",
    url: "/tours/lake-naivasha-boat-safari",
    region: "East Africa",
    country: "Kenya",
    highlights: ["Boat Safari", "Hippo Viewing", "Bird Watching", "Crescent Island Walk"],
    included: ["Boat safari", "Guide", "Park fees", "Lunch"],
    excluded: ["Tips"],
    itinerary: [
      { day: 1, title: "Lake Naivasha Exploration", description: "Boat safari and island walking tour." },
    ],
    rating: 4.3,
    reviewCount: 61,
    metaTitle: "Lake Naivasha Boat Safari - 1 Day | Jae Travel Expeditions",
    metaDescription: "Boat safari on freshwater Lake Naivasha.",
    keywords: ["Lake Naivasha", "Boat Safari", "Kenya", "Crescent Island", "Hippo Tour"],
    bookingUrl: "/booking/lake-naivasha-boat-safari",
    category: "Adventure",
    featured: false,
    name: "Lake Naivasha Boat Safari",
    destinations: ["Lake Naivasha"],
    bestTime: ["Year-round"],
    priceFrom: 150
  },
  {
    id: "44",
    slug: "kenya-disability-safari",
    image: "/wheelchair-accessible-tanzania-safari.webp",
    title: "Accessible Kenya Safari Experience",
    description: "A fully accessible safari experience designed for travelers with mobility challenges, featuring wheelchair-accessible vehicles, accommodations, and tailored wildlife viewing.",
    price: 2450,
    currency: "USD",
    duration: "7 days",
    groupSize: "2-6",
    difficulty: "Easy",
    url: "/tours/kenya-disability-safari",
    region: "East Africa",
    country: "Kenya",
    highlights: ["Accessible Vehicles", "Wheelchair-Friendly Lodges", "Tailored Game Drives", "Expert Guides"],
    included: ["Accessible vehicles", "Accommodation", "Meals", "Park fees", "Guide"],
    excluded: ["Flights", "Tips"],
    itinerary: [
      { day: 1, title: "Arrival & Orientation", description: "Accessible transfer and briefing." },
      { day: 2, title: "Nairobi National Park", description: "Accessible game drives." },
      { day: 3, title: "Lake Naivasha", description: "Boat safari and bird watching." },
      { day: 4, title: "Masai Mara Transfer", description: "Accessible travel to Mara." },
      { day: 5, title: "Masai Mara Game Drives", description: "Tailored wildlife viewing." },
      { day: 6, title: "Masai Mara Full Day", description: "Continued exploration." },
      { day: 7, title: "Departure", description: "Return to Nairobi and fly out." },
    ],
    rating: 4.8,
    reviewCount: 42,
    metaTitle: "Accessible Kenya Safari Experience for People with Disabilities | Jae Travel Expeditions",
    metaDescription: "Fully accessible safari experience with wheelchair-accessible vehicles in Kenya.",
    keywords: ["Accessible Safari Kenya", "Disability Travel Kenya", "Wheelchair Safari", "Accessible Wildlife Tours"],
    bookingUrl: "/booking/kenya-disability-safari",
    category: "Accessible",
    featured: true,
    name: "Accessible Kenya Safari Experience",
    destinations: ["Nairobi National Park", "Lake Naivasha", "Masai Mara"],
    bestTime: ["Year-round"],
    priceFrom: 2450
  },
  {
    id: "45",
    slug: "accessible-masai-mara-safari",
    image: "/Tineke-in-Kenya.png",
    title: "4-Day Accessible Masai Mara Experience",
    description: "A focused accessible safari in the Masai Mara with wheelchair-adapted vehicles, accessible tented camps, and front-row seats to the Great Migration.",
    price: 1450,
    currency: "USD",
    duration: "4 days",
    groupSize: "2-6",
    difficulty: "Easy",
    url: "/tours/accessible-masai-mara-safari",
    region: "East Africa",
    country: "Kenya",
    highlights: ["Accessible Vehicles", "Great Migration", "Luxury Tented Camps", "Expert Guides"],
    included: ["Accessible vehicles", "Luxury accommodation", "Meals", "Park fees", "Guide"],
    excluded: ["Flights", "Tips"],
    itinerary: [
      { day: 1, title: "Arrival in Masai Mara", description: "Accessible transfer and camp setup." },
      { day: 2, title: "Full Day Game Drives", description: "Migration viewing and Big Five." },
      { day: 3, title: "Morning & Evening Drives", description: "Predator tracking and wildlife." },
      { day: 4, title: "Departure", description: "Final game drive and return." },
    ],
    rating: 4.9,
    reviewCount: 38,
    metaTitle: "Accessible Masai Mara Safari for People with Disabilities | Jae Travel Expeditions",
    metaDescription: "Accessible safari in Masai Mara with wheelchair-adapted vehicles.",
    keywords: ["Accessible Masai Mara", "Disability Safari Kenya", "Wheelchair Masai Mara", "Accessible Tours"],
    bookingUrl: "/booking/accessible-masai-mara-safari",
    category: "Accessible",
    featured: true,
    name: "Accessible Masai Mara Safari",
    destinations: ["Masai Mara National Reserve"],
    bestTime: ["July-October"],
    priceFrom: 1450
  },
  {
    id: "46",
    slug: "tanzania-accessible-safari",
    image: "/WhatsApp-Image-2025-01-15-at-12.06.45-PM.webp",
    title: "Tanzania Accessible Safari Adventure",
    description: "An inclusive journey through Tanzania's Serengeti and Ngorongoro Crater with adapted safari vehicles, accessible lodges, and unforgettable wildlife encounters.",
    price: 2950,
    currency: "USD",
    duration: "8 days",
    groupSize: "2-6",
    difficulty: "Easy",
    url: "/tours/tanzania-accessible-safari",
    region: "East Africa",
    country: "Tanzania",
    highlights: ["Accessible Vehicles", "Serengeti Plains", "Ngorongoro Crater", "Adapted Accommodations"],
    included: ["Accessible vehicles", "Accommodation", "Meals", "Park fees", "Guide"],
    excluded: ["Flights", "Tips"],
    itinerary: [
      { day: 1, title: "Arrival in Arusha", description: "Accessible transfer and briefing." },
      { day: 2, title: "Tarangire National Park", description: "Accessible game drives." },
      { day: 3, title: "Serengeti Transfer", description: "Travel to Serengeti." },
      { day: 4, title: "Serengeti Exploration", description: "Wildlife viewing on plains." },
      { day: 5, title: "Serengeti Full Day", description: "Continued safari experience." },
      { day: 6, title: "Ngorongoro Crater", description: "Accessible crater tour." },
      { day: 7, title: "Cultural Experiences", description: "Accessible community visits." },
      { day: 8, title: "Departure", description: "Return to Arusha and fly out." },
    ],
    rating: 4.7,
    reviewCount: 29,
    metaTitle: "Tanzania Accessible Safari Adventure | Jae Travel Expeditions",
    metaDescription: "Inclusive journey through Tanzania with adapted vehicles.",
    keywords: ["Accessible Tanzania Safari", "Disability Travel Tanzania", "Wheelchair Safari Tanzania", "Serengeti Accessible"],
    bookingUrl: "/booking/tanzania-accessible-safari",
    category: "Accessible",
    featured: true,
    name: "Tanzania Accessible Safari Adventure",
    destinations: ["Tarangire", "Serengeti", "Ngorongoro"],
    bestTime: ["June-October"],
    priceFrom: 2950
  },
  {
    id: "49",
    slug: "east-africa-grand-accessible-safari",
    image: "/ngorongoro-header-3.jpg",
    title: "East Africa Grand Accessible Safari",
    description: "The ultimate East African accessible safari across Kenya and Tanzania, combining Maasai Mara, Serengeti, and Ngorongoro with premium accessible accommodations.",
    price: 5800,
    currency: "USD",
    duration: "12 days",
    groupSize: "2-6",
    difficulty: "Easy",
    url: "/tours/east-africa-grand-accessible-safari",
    region: "East Africa",
    country: "Multi-Country",
    highlights: ["Accessible Vehicles", "Luxury Lodges", "Big Five", "Migration"],
    included: ["All transfers", "Accessible vehicles", "Meals", "Park fees", "Guide"],
    excluded: ["Flights", "Tips"],
    itinerary: [
      { day: 1, title: "Arrival in Nairobi", description: "Accessible transfer." },
      { day: 2, title: "Masai Mara", description: "Game drives." },
      { day: 3, title: "Masai Mara", description: "Full day." },
      { day: 4, title: "Masai Mara", description: "Morning drive." },
      { day: 5, title: "Fly to Serengeti", description: "Cross border." },
      { day: 6, title: "Serengeti", description: "Migration." },
      { day: 7, title: "Serengeti", description: "Game drives." },
      { day: 8, title: "Ngorongoro", description: "Crater tour." },
      { day: 9, title: "Ngorongoro", description: "Full day." },
      { day: 10, title: "Lake Manyara", description: "Accessible viewing." },
      { day: 11, title: "Arusha", description: "Rest day." },
      { day: 12, title: "Departure", description: "Fly home." },
    ],
    rating: 4.9,
    reviewCount: 18,
    metaTitle: "East Africa Grand Accessible Safari | Jae Travel Expeditions",
    metaDescription: "Ultimate East African accessible safari across Kenya and Tanzania.",
    keywords: ["East Africa Accessible Safari", "Multi-Country Safari", "Disability Travel East Africa", "Grand Safari"],
    bookingUrl: "/booking/east-africa-grand-accessible-safari",
    category: "Accessible",
    featured: true,
    name: "East Africa Grand Accessible Safari",
    destinations: ["Masai Mara", "Serengeti", "Ngorongoro", "Lake Manyara"],
    bestTime: ["July-October"],
    priceFrom: 5800
  },
  {
    id: "50",
    slug: "carnivore-experience",
    image: "/carnivore-dining.jpg",
    title: "Carnivore Experience",
    description: "Indulge in a unique dining adventure at the famous Carnivore Restaurant in Nairobi, featuring exotic game meats and vibrant Kenyan hospitality.",
    price: 150,
    currency: "USD",
    duration: "1 day",
    groupSize: "1-20",
    difficulty: "Easy",
    url: "/tours/carnivore-experience",
    region: "East Africa",
    country: "Kenya",
    highlights: ["Game Meats", "Live Music", "Kenyan Hospitality", "All-You-Can-Eat"],
    included: ["Dinner", "Transport", "Guide"],
    excluded: ["Drinks", "Tips"],
    itinerary: [
      { day: 1, title: "Carnivore Dinner", description: "Evening dining experience." },
    ],
    rating: 4.7,
    reviewCount: 25,
    metaTitle: "Carnivore Experience | Jae Travel Expeditions",
    metaDescription: "Unique dining adventure at Nairobi's Carnivore Restaurant.",
    keywords: ["Carnivore Restaurant", "Nairobi Dining", "Kenya Food Tour", "Game Meat Experience"],
    bookingUrl: "/booking/carnivore-experience",
    category: "Cultural",
    featured: false,
    name: "Carnivore Experience",
    destinations: ["Nairobi"],
    bestTime: ["Year-round"],
    priceFrom: 150
  },
  {
    id: "51",
    slug: "safari-madoa-doa",
    image: "/madoa-doa-safari.jpg",
    title: "Safari Madoa Doa",
    description: "Embark on an exclusive safari adventure through Kenya's premier wildlife reserves, spotting the Big Five in their natural habitat.",
    price: 3200,
    currency: "USD",
    duration: "7 days",
    groupSize: "2-8",
    difficulty: "Moderate",
    url: "/tours/safari-madoa-doa",
    region: "East Africa",
    country: "Kenya",
    highlights: ["Big Five", "Luxury Camps", "Private Guides", "Photography"],
    included: ["All meals", "Park fees", "Private 4x4", "Guide", "Flights"],
    excluded: ["International flights", "Tips"],
    itinerary: [
      { day: 1, title: "Arrival", description: "Nairobi." },
      { day: 2, title: "Amboseli", description: "Elephants." },
      { day: 3, title: "Amboseli", description: "Kilimanjaro views." },
      { day: 4, title: "Masai Mara", description: "Fly in." },
      { day: 5, title: "Masai Mara", description: "Full day." },
      { day: 6, title: "Masai Mara", description: "Migration." },
      { day: 7, title: "Departure", description: "Fly out." },
    ],
    rating: 4.8,
    reviewCount: 15,
    metaTitle: "Safari Madoa Doa | Jae Travel Expeditions",
    metaDescription: "Exclusive safari adventure through Kenya's premier wildlife reserves.",
    keywords: ["Kenya Safari", "Big Five Safari", "Wildlife Adventure", "Madoa Doa Safari"],
    bookingUrl: "/booking/safari-madoa-doa",
    category: "Safari",
    featured: false,
    name: "Safari Madoa Doa",
    destinations: ["Amboseli National Park", "Masai Mara National Reserve"],
    bestTime: ["July-October"],
    priceFrom: 3200
  },
  {
    id: "52",
    slug: "best-of-zanzibar",
    image: "/zanzibar-beach.jpg",
    title: "Best of Zanzibar",
    description: "Discover the tropical paradise of Zanzibar with its pristine beaches, historic Stone Town, and vibrant spice tours.",
    price: 2500,
    currency: "USD",
    duration: "8 days",
    groupSize: "2-10",
    difficulty: "Easy",
    url: "/tours/best-of-zanzibar",
    region: "East Africa",
    country: "Tanzania",
    highlights: ["Stone Town", "Spice Tour", "Beaches", "Dhow Cruise"],
    included: ["All meals", "Tours", "Accommodation", "Transfers"],
    excluded: ["Flights", "Tips"],
    itinerary: [
      { day: 1, title: "Arrival & Stone Town", description: "Historic tour." },
      { day: 2, title: "Spice Tour", description: "Farm visit." },
      { day: 3, title: "Beach Transfer", description: "East coast." },
      { day: 4, title: "Beach Relaxation", description: "Free day." },
      { day: 5, title: "Snorkeling", description: "Mnemba Atoll." },
      { day: 6, title: "Dhow Cruise", description: "Sunset." },
      { day: 7, title: "Beach", description: "Final day." },
      { day: 8, title: "Departure", description: "Fly out." },
    ],
    rating: 4.9,
    reviewCount: 22,
    metaTitle: "Best of Zanzibar | Jae Travel Expeditions",
    metaDescription: "Tropical paradise of Zanzibar with beaches and Stone Town.",
    keywords: ["Zanzibar Tour", "Stone Town", "Spice Tour", "Tanzania Beach Holiday"],
    bookingUrl: "/booking/best-of-zanzibar",
    category: "Beach",
    featured: true,
    name: "Best of Zanzibar",
    destinations: ["Zanzibar Island"],
    bestTime: ["June-October", "December-March"],
    priceFrom: 2500
  },
  {
    id: "53",
    slug: "classic-sky-safari-2",
    image: "/sky-safari.jpg",
    title: "Classic Sky Safari 2",
    description: "Soar above East Africa's iconic landscapes on a luxury sky safari, visiting Amboseli, Meru, and the Maasai Mara.",
    price: 6500,
    currency: "USD",
    duration: "10 days",
    groupSize: "2-6",
    difficulty: "Easy",
    url: "/tours/classic-sky-safari-2",
    region: "East Africa",
    country: "Kenya",
    highlights: ["Private Flights", "Luxury Lodges", "Big Five", "Aerial Views"],
    included: ["All flights", "Meals", "Game drives", "Luxury stays"],
    excluded: ["International flights", "Tips"],
    itinerary: [
      { day: 1, title: "Arrival Nairobi", description: "Welcome." },
      { day: 2, title: "Fly to Amboseli", description: "Kilimanjaro." },
      { day: 3, title: "Amboseli", description: "Game drives." },
      { day: 4, title: "Fly to Meru", description: "Remote wilderness." },
      { day: 5, title: "Meru", description: "Rhino sanctuary." },
      { day: 6, title: "Fly to Masai Mara", description: "Migration." },
      { day: 7, title: "Masai Mara", description: "Full day." },
      { day: 8, title: "Masai Mara", description: "Balloon option." },
      { day: 9, title: "Masai Mara", description: "Final drives." },
      { day: 10, title: "Departure", description: "Fly home." },
    ],
    rating: 5.0,
    reviewCount: 12,
    metaTitle: "Classic Sky Safari 2 | Jae Travel Expeditions",
    metaDescription: "Luxury sky safari over Kenya's iconic landscapes.",
    keywords: ["Sky Safari", "Luxury Safari Kenya", "Maasai Mara", "Amboseli Tour", "Aerial Safari"],
    bookingUrl: "/booking/classic-sky-safari-2",
    category: "Luxury",
    featured: true,
    name: "Classic Sky Safari 2",
    destinations: ["Amboseli National Park", "Meru National Park", "Masai Mara National Reserve"],
    bestTime: ["July-October"],
    priceFrom: 6500
  },
  {
    id: "54",
    slug: "nairobi-national-park-tour",
    image: "/nairobi-park.jpg",
    title: "Nairobi National Park Tour",
    description: "Explore Nairobi National Park, a unique wildlife haven near the city, home to rhinos, lions, and stunning savanna views.",
    price: 200,
    currency: "USD",
    duration: "1 day",
    groupSize: "1-15",
    difficulty: "Easy",
    url: "/tours/nairobi-national-park-tour",
    region: "East Africa",
    country: "Kenya",
    highlights: ["Rhinos", "Lions", "City Skyline", "Birds"],
    included: ["Park fees", "Guide", "Transport", "Lunch"],
    excluded: ["Tips"],
    itinerary: [
      { day: 1, title: "Nairobi National Park", description: "Morning game drive." },
    ],
    rating: 4.6,
    reviewCount: 30,
    metaTitle: "Nairobi National Park Tour | Jae Travel Expeditions",
    metaDescription: "Unique wildlife haven near Nairobi with rhinos and lions.",
    keywords: ["Nairobi National Park", "Kenya Wildlife Tour", "Day Safari Nairobi", "Rhino Safari"],
    bookingUrl: "/booking/nairobi-national-park-tour",
    category: "Safari",
    featured: false,
    name: "Nairobi National Park Tour",
    destinations: ["Nairobi National Park"],
    bestTime: ["Year-round"],
    priceFrom: 200
  },
  {
    id: "55",
    slug: "visit-a-thousand-hills-distilleries",
    image: "/thousand-hills-distillery.jpg",
    title: "Visit a Thousand Hills Distilleries",
    description: "Experience Rwanda's artisanal spirit scene with a tour of Thousand Hills Distilleries, tasting premium local beverages.",
    price: 100,
    currency: "USD",
    duration: "1 day",
    groupSize: "1-10",
    difficulty: "Easy",
    url: "/tours/visit-a-thousand-hills-distilleries",
    region: "East Africa",
    country: "Rwanda",
    highlights: ["Gin Tasting", "Rum", "Local Spirits", "Tour"],
    included: ["Tasting", "Guide", "Transport"],
    excluded: ["Tips"],
    itinerary: [
      { day: 1, title: "Distillery Tour", description: "Taste and learn." },
    ],
    rating: 4.5,
    reviewCount: 10,
    metaTitle: "Visit a Thousand Hills Distilleries | Jae Travel Expeditions",
    metaDescription: "Rwanda's artisanal spirit scene at Thousand Hills Distilleries.",
    keywords: ["Rwanda Distillery Tour", "Thousand Hills Distillery", "Local Spirits Rwanda", "Cultural Tour Rwanda"],
    bookingUrl: "/booking/visit-a-thousand-hills-distilleries",
    category: "Cultural",
    featured: false,
    name: "Visit a Thousand Hills Distilleries",
    destinations: ["Kigali"],
    bestTime: ["Year-round"],
    priceFrom: 100
  },
  {
    id: "56",
    slug: "this-is-africa-nyamirambo-womens-center",
    image: "/nyamirambo-center.jpg",
    title: "Nyamirambo Women's Center",
    description: "Immerse yourself in Rwandan culture with a visit to Nyamirambo Women's Center, exploring local crafts and community initiatives.",
    price: 80,
    currency: "USD",
    duration: "1 day",
    groupSize: "1-12",
    difficulty: "Easy",
    url: "/tours/this-is-africa-nyamirambo-womens-center",
    region: "East Africa",
    country: "Rwanda",
    highlights: ["Crafts", "Community", "Local Life", "Walking Tour"],
    included: ["Guide", "Lunch", "Transport"],
    excluded: ["Tips"],
    itinerary: [
      { day: 1, title: "Nyamirambo Tour", description: "Walking and crafts." },
    ],
    rating: 4.8,
    reviewCount: 15,
    metaTitle: "Nyamirambo Women's Center Tour | Jae Travel Expeditions",
    metaDescription: "Rwandan culture and crafts at Nyamirambo Women's Center.",
    keywords: ["Nyamirambo Women's Center", "Rwanda Cultural Tour", "Kigali Community Tour", "African Crafts"],
    bookingUrl: "/booking/this-is-africa-nyamirambo-womens-center",
    category: "Cultural",
    featured: false,
    name: "Nyamirambo Women's Center Tour",
    destinations: ["Kigali"],
    bestTime: ["Year-round"],
    priceFrom: 80
  },
  {
    id: "57",
    slug: "relaxation-at-the-beach",
    image: "/beach-relaxation.jpg",
    title: "Relaxation at the Beach",
    description: "Unwind on the pristine beaches of East Africa, enjoying sun, sand, and sea in a serene coastal escape.",
    price: 1200,
    currency: "USD",
    duration: "5 days",
    groupSize: "2-10",
    difficulty: "Easy",
    url: "/tours/relaxation-at-the-beach",
    region: "East Africa",
    country: "Tanzania",
    highlights: ["White Sand", "Clear Water", "Sunset", "Spa"],
    included: ["Accommodation", "Meals", "Transfers"],
    excluded: ["Flights", "Tips"],
    itinerary: [
      { day: 1, title: "Arrival", description: "Beach resort." },
      { day: 2, title: "Relaxation", description: "Free day." },
      { day: 3, title: "Beach", description: "Sun and sea." },
      { day: 4, title: "Spa Day", description: "Optional." },
      { day: 5, title: "Departure", description: "Fly out." },
    ],
    rating: 4.7,
    reviewCount: 20,
    metaTitle: "Relaxation at the Beach | Jae Travel Expeditions",
    metaDescription: "Pristine beaches of East Africa for coastal retreat.",
    keywords: ["Beach Holiday East Africa", "Coastal Retreat", "Tanzania Beach Tour", "Relaxation Tour"],
    bookingUrl: "/booking/relaxation-at-the-beach",
    category: "Beach",
    featured: false,
    name: "Relaxation at the Beach",
    destinations: ["Zanzibar Coast"],
    bestTime: ["June-October", "December-March"],
    priceFrom: 1200
  },
  {
    id: "58",
    slug: "safari-dwika",
    image: "/dwika-safari.jpg",
    title: "Safari Dwika",
    description: "Join an adventurous safari through Tanzania's iconic parks, witnessing diverse wildlife and stunning landscapes.",
    price: 3500,
    currency: "USD",
    duration: "7 days",
    groupSize: "4-12",
    difficulty: "Moderate",
    url: "/tours/safari-dwika",
    region: "East Africa",
    country: "Tanzania",
    highlights: ["Serengeti", "Ngorongoro", "Tarangire", "Cultural Visits"],
    included: ["Park fees", "Meals", "Game drives", "Guide", "Transfers"],
    excluded: ["Flights", "Visa", "Tips"],
    itinerary: [
      { day: 1, title: "Arrival in Arusha", description: "Welcome and briefing." },
      { day: 2, title: "Tarangire National Park", description: "Elephants and baobabs." },
      { day: 3, title: "Lake Manyara", description: "Tree-climbing lions." },
      { day: 4, title: "Serengeti", description: "Migration tracking." },
      { day: 5, title: "Serengeti Full Day", description: "Big cats and plains." },
      { day: 6, title: "Ngorongoro Crater", description: "Full-day crater tour." },
      { day: 7, title: "Departure", description: "Fly out from Arusha." },
    ],
    rating: 4.8,
    reviewCount: 18,
    metaTitle: "Safari Dwika | Jae Travel Expeditions",
    metaDescription: "Adventurous safari through Tanzania's iconic wildlife parks.",
    keywords: ["Tanzania Safari", "Wildlife Tour", "Dwika Safari", "East Africa Adventure"],
    bookingUrl: "/booking/safari-dwika",
    category: "Safari",
    featured: false,
    name: "Safari Dwika",
    destinations: ["Tarangire", "Lake Manyara", "Serengeti", "Ngorongoro"],
    bestTime: ["June-October", "December-March"],
    priceFrom: 3500
  },
]

// === FILTERED EXPORTS ===
export const disabilityTours = tours.filter((tour) => tour.category === "Accessible")

export const toursByCountry = {
  Kenya: tours.filter((t) => t.country === "Kenya"),
  Tanzania: tours.filter((t) => t.country === "Tanzania"),
  Rwanda: tours.filter((t) => t.country === "Rwanda"),
  Uganda: tours.filter((t) => t.country === "Uganda"),
  "Multi-Country": tours.filter((t) => t.country === "Multi-Country"),
} satisfies Record<string, Tour[]>

export const toursOnOffer = tours.filter((tour) => tour.isOnOffer === true)